### ISSUE TITLE
Bundled app initialization error (vs 15.7 preview)

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#1651]
### Steps to Reproduce

1. Create a xamarin app for Android
2. Enable "Bundle Assemblies into Native Code" option : <BundleAssemblies>true</BundleAssemblies> in csproj
3. Build and launch app in VS 2017 15.7 preview

### Expected Behavior

No crash.
This is actually what happens with VS 2017 15.6.7

### Actual Behavior

App crashes (when using VS 2017 15.7 preview) with the following error:
bundled app initialization error: dlopen failed: cannot locate symbol "mono_jit_set_aot_mode" referenced by libmonodroid_bundle_app.so

### Version Information (causing the error)

Version 15.7.0 Preview 5.0
VisualStudio.15.Preview/15.7.0-pre.5.0+27625.0
Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Xamarin   4.10.0.440 (943b34d9d)
Xamarin.Android SDK   8.3.0.18 (HEAD/1f8462ef1)

### Version Information (no error)

Version 15.6.7
VisualStudio.15.Release/15.6.7+27428.2043
Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Xamarin   4.9.0.753 (f0f46392f)
Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)

> VS bug [#618947](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/618947)

**Comment by whitwa** [comment]
This is also happening with the release of version 15.7.0.

Microsoft Visual Studio Enterprise 2017 Version 15.7.0
VisualStudio.15.Release/15.7.0+27703.1
Mono Debugging for Visual Studio 4.10.5-pre (ab58725)
Xamarin 4.10.0.442 (396b18cef)
Xamarin.Android SDK 8.3.0.19 (HEAD/342b2ce96)

**Comment by RajGogri** [comment]
This is also happening with the release of VS 2017 community edition. 

Visual Studio Community 2017 for Mac
Version 7.5 (build 1254)
Installation UUID: e1436f78-c6f3-45bb-883a-d0fd263fac97
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Community)

Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/webwerks/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 28.0.0 rc1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

**Comment by jgold6** [comment]
I received another report of this and was able to reproduce both on Visual Studio 2017 Windows and VS for Mac (all updated to 15.7) with a template Xamarin.Forms app. I am attaching adb logcat log that show the error and a test project. 

## VS 2017 Windows version info:
Microsoft Visual Studio Enterprise 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-90253-02232-AA699
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-90253-02232-AA699
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.21208.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.5
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.5
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.5.1.2234
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.3000.5
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.5
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.1
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.5
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

OptionsPackage Extension   1.0
OptionsPackage Visual Studio Extension Detailed Info

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


## Vs for Mac version info:
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.5 (build 1254)
Installation UUID: f86726f2-bd5d-4610-867e-44e82f306ca2
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.1
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.1.176 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.10.1.177 (Visual Studio Enterprise)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/jongoldberger/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.2   (API level 17)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1


## Test Project
[TestProject.zip](https://github.com/xamarin/xamarin-android/files/1989878/TestProject.zip)

## ADB Logcat logs
[EmbedAssembliesIntoNativeCodeCrash.txt](https://github.com/xamarin/xamarin-android/files/1989882/EmbedAssembliesIntoNativeCodeCrash.txt)

**Comment by HakanCelikMK1** [comment]
I'm also suffering from the same problem, after I updated my Visual Studio installation to 15.7.1 this morning. I couldn't get the release version of my Android project to work.

This doesn't seem to be an edge case. How can such an obvious  problem escape the testing ? 
@RajGogri thank you for poviding a workaround, you've saved me a lot of time.

My environment :
Windows 10 Enterprise x64, 1709, 16299.431
Microsoft Visual Studio Enterprise 2017 Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET FrameworkVersion 4.7.03062
Xamarin   4.10.0.442 (396b18cef)
Xamarin Designer   4.12.264 (fc37cd02e)
Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)

**Comment by gjkhw** [comment]
I also see the issue. I just did a clean install of VS2017 for Mac 7.5 to be sure.

<details>
  <summary>Click for a long list of "About" text from VS2017 for Mac...</summary>

Visual Studio Professional 2017 for Mac
Version 7.5 (build 1254)
Installation UUID: b05a38fd-8fe4-4390-b9b3-0c464dbea029
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Professional)

Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Professional)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Professional)
Android SDK: /Users/e840944/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1
</details>

**Comment by brendanzagaeski** [comment]
Cross-referencing note for the Microsoft team

A matching error message has also been reported in: <https://developercommunity.visualstudio.com/content/problem/249954/build-release-xamarin-android-error-if-check-budle.html>

**Comment by jzeferino** [comment]
Having the same problem here.

**Comment by jonpryor** [comment]
The immediate cause of the breakage is this change to `mkbundle`: https://github.com/mono/mono/commit/ca8b8bd346a6

It altered `mkbundle` output so that it now had a call to `mono_jit_set_aot_mode()`, which results in an undefined symbol in mkbundle output:

```
$ …/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-nm -D obj/Debug/bundles/armeabi-v7a/libmonodroid_bundle_app.so | grep mono_
         U mono_jit_set_aot_mode
00000ed8 T mono_mkbundle_init
```

This is what results in the `dlopen failed: cannot locate symbol "mono_jit_set_aot_mode"` message in `adb logcat`.

*Furthermore*, that mkbundle change (or an earlier one, I haven't dug deeper) has altered the API between xamarin-android and mkbundle output. [Xamarin.Android expects](https://github.com/xamarin/xamarin-android/blob/f5412f0efcabec586a02e75938b547e61e889c11/src/monodroid/jni/monodroid-glue.c#L2636) a [`mono_mkbundle_init()` declaration](https://github.com/xamarin/xamarin-android/blob/f5412f0efcabec586a02e75938b547e61e889c11/src/monodroid/jni/monodroid-glue.c#L685) of:

```c
typedef void (*mono_register_bundled_assemblies_fn)(const MonoBundledAssembly **);
typedef void (*mono_register_config_for_assembly_fn)(const char* assembly_name, const char* config_xml);

typedef void (*mono_mkbundle_init_ptr) (mono_register_bundled_assemblies_fn, mono_register_config_for_assembly_fn);
```

The `mono_mkbundle_init` that `mkbundle` emits, meanwhile, uses *no* parameters.

Furthermore, now that `mkbundle` wants to invoke `mono_jit_set_aot_mode()`, that will *also* need to be provided as a parameter to `mono_mkbundle_init`, thus removing the import from the generated `libmonodroid_bundle_app.so`.

**Comment by fekberg** [comment]
@jonpryor Any workaround for this? Seems to be an issue in both STABLE and Beta.

**Comment by jzeferino** [comment]
@fekberg atm the only workaround i know is to set "Bundle Assemblies into Native Code" to false por downgrade your mono version.

**Comment by ninaada** [comment]
When will this be fixed? We are stuck, not able to make release builds.

**Comment by RajGogri** [comment]
@ninaada @fekberg You can set **BundleAssemblies** flag to **false** for release config in Android's .csproj file. For the time being you can use this work around for running release build.

**Comment by fekberg** [comment]
@RajGogri That's a terrible workaround. There's a reason BundleAssemblies is set to true..

**Comment by grendello** [comment]
@EmilAlipiev the issue is caused by a breaking change in Mono, but we've fixed it entirely within Xamarin.Android, see https://github.com/xamarin/xamarin-android/pull/1683

**Comment by EmilAlipiev** [comment]
@grendello cool. please let us know when it is merged and published in any version. thank you

**Comment by grendello** [comment]
The PR has been committed to [Xamarin.Android/master](https://github.com/xamarin/xamarin-android/commit/1a45e1e2cdcbea84a024e86cdfabe9538763fafc)

**Comment by EmilAlipiev** [comment]
So are we expecting a VS2017 update soon? or xamarin android update? this is really taking so long and holding us to to do updates.. now weekend and we lose another week. thank you for your quick update

**Comment by ninaada** [comment]
Any time frame as to when we will get this update? We ran out of quota in the app center also & currently have no way of making builds without turning off Bundle assemblies, which we really don't want to do.

**Comment by JeroenBer** [comment]
This is also causing big problems for our app now, we need to do a new release but turn off bundle assemblies is not an option. Please fix asap.

**Comment by daniels7** [comment]
Come on Microsoft, this problem especially affects VS 2017 Enterprise Edition (and is one of the killer features of Xamarin on VS Enterprise) and each license costs several thousand Euros and still the issue is existing since several weeks... That's a no go! I don't understand how this error could ever pass your QA, since it is in normal release versions and not just Insider Previews or something... Fix this asap..please

**Comment by brendanzagaeski** [comment]
**Non-engineering-team cross-referencing notes about open source builds**

Since by chance I have a moment this weekend, I'll add a little information that might be of interest to some users over the weekend.

- [xamarin-android-builds-d15-7/22](https://jenkins.xamarin.com/view/Xamarin.Android/job/xamarin-android-builds-d15-7/22/PublishUrls/) lists the preliminary un-tested continuous integration packages from the Xamarin team open source build server that include the candidate fix.
- See also [the commit comparison](https://github.com/xamarin/xamarin-android/compare/a305bd2bbc064cd9d2b814137cd0d61bac54deac...3a020ba4df95dee37d14512c9946d33744078e90) between these packages and the current version in Visual Studio 2017 version 15.7. In short, there is one new commit for this issue.

The team is of course coordinating to include this change into Visual Studio as soon as possible, so many users will likely prefer to wait for that. 

But if some users would like to try the packages earlier, that is possible. Note that these steps do fall outside of the support policy. I also haven't had a chance to try this preliminary .vsix package myself. (I have used other preliminary Xamarin.Android .vsix packages successfully in the past.) If you would like to test this package locally, I would recommend installing it into a separate instance of Visual Studio (such as the Preview instance) if possible to avoid potential .vsix versioning conflicts when the fix is included into Visual Studio in an upcoming servicing release. You can revert the temporary .vsix installation under the **Tools > Extensions and Updates >  Installed** menu if needed. (In theory, reverting the test package before updating is also sufficient to avoid versioning conflicts.) In Visual Studio for Mac, if you wish to revert the test .pkg, you can reinstall the current Stable channel version using the [updater](https://docs.microsoft.com/visualstudio/mac/update) as usual.

(These steps are closely related to the guide on [Installing Jenkins Build Artifacts](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md).)

**Comment by JonDouglas** [comment]
At this time, we have a fix that will be available in **Visual Studio 15.7.3(Service Release 3)** as our fix did not make the cutoff window for 15.7.2(Service Release 2). The release history can be found [here](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes). Here's a quick note regarding service updates with respect to a timeframe:

> Servicing Updates are very targeted releases that typically contain bug fixes and ship more quickly. These servicing updates can ship often (e.g. weekly). You’ll be able to tell which servicing update you’re running by opening the Help, About and reading the third string in the version, for example 15.1.x, 15.2.y.

https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-release-rhythm

To unblock app releases, you can follow @brendanzagaeski [comment](https://github.com/xamarin/xamarin-android/issues/1651#issuecomment-390505705) on [Installing Jenkins Build Artifacts](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/JenkinsBuildArtifacts.md) until this releases through Visual Studio.

**Comment by abdu292** [comment]
Oh, I see. Thanks for the update!

**Comment by Foxsterc** [comment]
Downloading the vsix, as suggested by @brendanzagaeski, solved this issue for me on Visual Studio 15.7.2

**Comment by ronpf** [comment]
Seeing this in VSMac 7.5.1 (build 22)
When will the fix be for VSMac? Can't release app...

**Comment by fernandovm** [comment]
I have tested with the vsix, as suggested by @brendanzagaeski, but it not solve my problem. Unfortunately this is the third time that I update my VS and I'm have blocked without to can generate appstore releases. :((

**Comment by HakanCelikMK1** [comment]
I can confirm that Xamarin.Android.Sdk.8.3.2.0.vsix provided in the @brendanzagaeski's answer fixes the problem in my VS 2017 15.7.2 installation.

My environment :
OS : Windows 10 Enterprise x64, 1709, 16299.431

VS Info Before Install :
Microsoft Visual Studio Enterprise 2017 Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework Version 4.7.03062
Xamarin 4.10.0.442 (396b18cef)
Xamarin Designer 4.12.264 (fc37cd02e)
Xamarin.Android SDK 8.3.0.19 (HEAD/342b2ce96)

VS Info After Install :
Microsoft Visual Studio Enterprise 2017 Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework Version 4.7.03062
**Xamarin 4.10.0.448 (4373404db)
Xamarin Designer 4.12.270 (82d750d12)
Xamarin.Android SDK 8.3.2.0 (HEAD/8be583805)**

Cheers.

**Comment by mclillill** [comment]
Thanks. I had an install error. Then VS didn't start. Then tried installing the vsix again. It said "already installed". Then VS started again and I now have 8.3.2.0 installed. I didn't test yet though.

**Comment by mclillill** [comment]
It works in relase mode. But debug mode now only works with "Shared Runtime" turned off. Not sure if related...

**Comment by xufeipyxis** [comment]
I see v15.7.3 is released but I don't see this issue is fixed?
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.7.3

**Comment by abdu292** [comment]
Oh. Isn't it really fixed?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JeroenBer** [comment]
I installed 15.7.3 and it is working for me now.

**Comment by fernandovm** [comment]
Dear... Now I can generate appstore releases again, but unfortunately I can't explain exactaly the reason to be used as workaround. I have tested with the vsix, as suggested by @brendanzagaeski, but it not solve my problem. Then I have updated my project to Xamarin Forms 3 and indeed, it works, but I had other minor problems. Then I have downgraded my project to previous Xamarin Forms (2.5) and, without neither hope I have tried rebuild again, but, to my surprise, all worked fine.

**Comment by EmilAlipiev** [comment]
Hi, Please reopen this bug. it still doesnt work. this error occurs https://github.com/xamarin/xamarin-android/issues/1760

This is surely related to this problem. when I see the logs, i am seeing this information. what is that supposed to mean? what ArchiveListViewModel and what key does it expect?

```

Xamarin.VisualStudio.Progress.ProgressReportService|Information|0|Shared Mono runtime is enabled for ''.
Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel|Error|0|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xamarin.VisualStudio.Publishing.Presentation.ViewModels.ArchiveListViewModel.<<SubscribeToEvents>b__56_5>d.MoveNext() in E:\A\_work\5\s\src\Core\VisualStudio.Publishing\Presentation\ViewModels\ArchiveListViewModel.cs:line 262
Xamarin.VisualStudio.Progress.ProgressReportService|Information|0|The selected build configuration is using the shared Mono runtime for faster deployment. Apps cannot be archived with this setting enabled.
Xamarin.VisualStudio.Progress.ProgressReportService|Information|0|Please ensure that you are using a release configuration and that the "Use Shared Mono Runtime" option in your project's build options is unchecked.

```
