### ISSUE TITLE
Build with Linking is Crashing in Xamarin.Android 9.5

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-android#3387]
### Steps to Reproduce

1. Select Linker Behavior: Link SDK Assemblies or Link all assemblies.
2. Right click, Build or Rebuild.

### Expected Behavior

Compile.

### Actual Behavior

Not compiling.

<img width="1248" alt="Screen Shot 2019-07-25 at 07 55 22" src="https://user-images.githubusercontent.com/1666156/61849514-d48d8680-aeb1-11e9-9e50-394daf039983.png">

**It works if you don't link the assemblies.**

### Version Information

    Visual Studio Community 2019 for Mac (Preview)
    Version 8.3 Preview (8.3 build 867)
    Installation UUID: ab22eab5-59c2-461c-9611-0304860470f2
        GTK+ 2.24.23 (Raleigh theme)
        Xamarin.Mac 5.16.0.5 (d16-3 / 26f04c54)

        Package version: 604000081

    Mono Framework MDK
    Runtime:
        Mono 6.4.0.81 (2019-06/f55e0a671c0) (64-bit)
        Package version: 604000081

    NuGet
    Version: 5.2.0.6067

    .NET Core
    Runtime: /usr/local/share/dotnet/dotnet
    Runtime Versions:
        2.1.12
        2.1.11
        2.1.9
        2.1.8
        2.1.7
        2.1.6
        2.1.2
        2.1.1
        2.0.5
        2.0.0
        1.1.2
        1.0.5
    SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
    SDK Versions:
        2.1.701
        2.1.700
        2.1.505
        2.1.504
        2.1.503
        2.1.500
        2.1.302
        2.1.301
        2.1.4
        2.0.0
        1.0.4
    MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

    Xamarin.Profiler
    Version: 1.6.10
    Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

    Updater
    Version: 11

    Xamarin.Android
    Version: 9.5.0.27 (Visual Studio Community)
    Commit: xamarin-android/d16-3/16c4494
    Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
        Supported Android versions:
            8.1 (API level 27)

    SDK Tools Version: 26.1.1
    SDK Platform Tools Version: 29.0.1
    SDK Build Tools Version: 27.0.3

    Build Information: 
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

    Microsoft Mobile OpenJDK
    Java SDK: /Users/fanmixco/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
    1.8.0-25
    Android Designer EPL code available here:
    https://github.com/xamarin/AndroidDesigner.EPL

    Android SDK Manager
    Version: 1.4.0.8
    Hash: 28342d0
    Branch: remotes/origin/backport-pr-235-to-d16-3~2
    Build date: 2019-07-18 16:54:46 UTC

    Android Device Manager
    Version: 1.2.0.75
    Hash: bf6d603
    Branch: remotes/origin/backport-pr-369-to-d16-3~1
    Build date: 2019-07-18 16:55:08 UTC

    Xamarin Inspector
    Version: 1.4.3
    Hash: db27525
    Branch: 1.4-release
    Build date: Mon, 09 Jul 2018 21:20:18 GMT
    Client compatibility: 1

    Apple Developer Tools
    Xcode 10.3 (14492.2)
    Build 10G8

    Xamarin.Mac
    Version: 5.16.0.5 (Visual Studio Community)
    Hash: 26f04c54
    Branch: d16-3
    Build date: 2019-06-28 01:31:14-0400

    Xamarin.iOS
    Version: 12.16.0.5 (Visual Studio Community)
    Hash: 26f04c54
    Branch: d16-3
    Build date: 2019-06-28 01:31:14-0400

    Xamarin Designer
    Version: 16.3.0.17
    Hash: 73f0a446c
    Branch: remotes/origin/d16-3-release-8.3-p1
    Build date: 2019-07-22 17:05:22 UTC

    Build Information
    Release ID: 803000867
    Git revision: ab4af85ea561e474b545e0eada75c5bfe8a92297
    Build date: 2019-07-24 14:13:44+00
    Build branch: release-8.3-preview1
    Xamarin extensions: 45290013e165bcd2db7acbb310e0c16bfe04f0c3

    Operating System
    Mac OS X 10.14.5
    Darwin 18.6.0 Darwin Kernel Version 18.6.0
        Thu Apr 25 23:16:27 PDT 2019
        root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by FANMixco** [comment]
The projects are here:

https://github.com/xamarin/xamarin-android/issues/3263#issuecomment-514046705

And now one of my libraries is not even rendering:

![Untitled](https://user-images.githubusercontent.com/1666156/61850663-21bf2780-aeb5-11e9-91f6-7b034cfa3792.png)

Before:

![Untitled1](https://user-images.githubusercontent.com/1666156/61850679-2683db80-aeb5-11e9-8804-8eb9e7d83564.png)

The library:

https://github.com/FANMixco/Xamarin-SearchBar

**Comment by JonDouglas** [comment]
Within Xamarin.Android 9.5(Preview), there is a new version of Mono(6.4). It's very likely that Mono introduced a regression with regards to the linker that we will need to look at.

Thank you well in advance for reporting this issue. That way we can ensure this is fixed in a future preview.

**Comment by brendanzagaeski** [comment]
Thanks for the report! The "The "LinkAssemblies" task failed unexpectedly" error is caused by following element in the *TipSal.csproj* file:

```xml
<RunCodeAnalysis>true</RunCodeAnalysis> 
```

This problem is being tracked in <https://github.com/xamarin/xamarin-android/issues/3322>. To resolve the issue for now, either remove the element by editing the *.csproj* file in a text editor, or set the property to false by unchecking the **Project Options > Code Analysis > Enable Code Analysis on Build** setting in Visual Studio for Mac.

* * *

> And now one of my libraries is not even rendering

Thanks for the information about this other problem too! I was able to reproduce this issue, so I minimized the scenario, filed it in its own issue <https://github.com/xamarin/xamarin-android/issues/3395>, and submitted a candidate fix <https://github.com/xamarin/xamarin-android/pull/3396>.

One possible way to work around that issue for now is to switch the project back to using AAPT instead of AAAPT2, for example by checking and unchecking the **Use incremental Android package system (aapt2)** setting in the Visual Studio project property pages and saving the changes.

* * *

With those 2 issues now tracked, I'll close this issue as a duplicate of <https://github.com/xamarin/xamarin-android/issues/3322>. Thanks again!

Duplicate of #3322

**Comment by FANMixco** [comment]
> Thanks for the report! The "The "LinkAssemblies" task failed unexpectedly" error is caused by following element in the _TipSal.csproj_ file:
> 
> ```
> <RunCodeAnalysis>true</RunCodeAnalysis> 
> ```
> 
> This problem is being tracked in #3322. To resolve the issue for now, either remove the element by editing the _.csproj_ file in a text editor, or set the property to false by unchecking the **Project Options > Code Analysis > Enable Code Analysis on Build** setting in Visual Studio for Mac.
> 
> > And now one of my libraries is not even rendering
> 
> Thanks for the information about this other problem too! I was able to reproduce this issue, so I minimized the scenario, filed it in its own issue #3395, and submitted a candidate fix #3396.
> 
> One possible way to work around that issue for now is to switch the project back to using AAPT instead of AAAPT2, for example by checking and unchecking the **Use incremental Android package system (aapt2)** setting in the Visual Studio project property pages and saving the changes.
> 
> With those 2 issues now tracked, I'll close this issue as a duplicate of #3322. Thanks again!
> 
> Duplicate of #3322

Thanks, I only have one comment, I'm not using the aapt2 in any of my projects:

<img width="734" alt="Screen Shot 2019-07-28 at 06 16 23" src="https://user-images.githubusercontent.com/1666156/62002188-4b6b8f00-b0ff-11e9-9319-7ba3bbfc9535.png">

**Comment by brendanzagaeski** [comment]
If somehow the `$(_UseManagedResourceGenerator)` MSBuild property is set to `true` for a project that is using AAPT, that would produce the same problem. By default, that property is `false` when using AAPT, but it is in theory possible that something outside of the Xamarin.Android MSBuild targets could change the value. A good place to check would be in the diagnostic MSBuild output from your project.

To get the diagnostic MSBuild output, rebuild the project in a Terminal.app command prompt. Use the `cd` command to change to the directory that contains your *.sln* file. Then run the build with a command similar to:

   ```sh
    msbuild "-flp:v=diag;logfile=$HOME/Desktop/msbuild.txt" -t:Rebuild -p:Configuration=Release
   ```

After the build completes, open the *msbuild.txt* from your Desktop in a text viewer. Look for the line that matches `Task Parameter:UseManagedResourceGenerator=`. If that line shows that the task parameter is indeed `false` but you're still getting incorrect return values from calling `GetString()` on the result of `ObtainStyledAttributes()`, then the next best step would be to create a [new issue](https://github.com/xamarin/xamarin-android/issues/new), attaching an example project that demonstrates the problem when `UseManagedResourceGenerator` is false. Thanks in advance!

**Comment by FANMixco** [comment]
> If somehow the `$(_UseManagedResourceGenerator)` MSBuild property is set to `true` for a project that is using AAPT, that would produce the same problem. By default, that property is `false` when using AAPT, but it is in theory possible that something outside of the Xamarin.Android MSBuild targets could change the value. A good place to check would be in the diagnostic MSBuild output from your project.
> 
> To get the diagnostic MSBuild output, rebuild the project in a Terminal.app command prompt. Use the `cd` command to change to the directory that contains your _.sln_ file. Then run the build with a command similar to:
> 
> ```shell
>  msbuild "-flp:v=diag;logfile=$HOME/Desktop/msbuild.txt" -t:Rebuild -p:Configuration=Release
> ```
> 
> After the build completes, open the _msbuild.txt_ from your Desktop in a text viewer. Look for the line that matches `Task Parameter:UseManagedResourceGenerator=`. If that line shows that the task parameter is indeed `false` but you're still getting incorrect return values from calling `GetString()` on the result of `ObtainStyledAttributes()`, then the next best step would be to create a [new issue](https://github.com/xamarin/xamarin-android/issues/new), attaching an example project that demonstrates the problem when `UseManagedResourceGenerator` is false. Thanks in advance!

I still have a bad feeling that if I am able to do it, then I'll trigger this issue: https://github.com/xamarin/xamarin-android/issues/3399 because both of my apps shared a lot of things in the home screen.
