### ISSUE TITLE
System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by todorspetkov** [xamarin/xamarin-android#4772]
### Description
Observing the following Exception in Firebase Crashlytics only on Android 5.0.x devices, 90% on Huawei devices. Release build (no shared mono runtime). Anyone seen somthething similar?

```
Fatal Exception: android.runtime.JavaProxyThrowable: System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <1b7a5cd4b5194667aea235f87b2a861e>:0 
  at System.Guid.NewGuid () [0x00000] in <1b7a5cd4b5194667aea235f87b2a861e>:0 
  Comune.InitializeComponent () [0x00182] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at xxx.Views.SelezioneComune..ctor (System.Boolean isCambia) [0x0000c] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at xxx.App.OnStart () [0x000aa] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at Xamarin.Forms.Application.SendStart () [0x00000] in <9608dd67eb804f0494e04a66ff90c168>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStateChanged () [0x0001b] in <63e7c9910ab446ac9b78b1ac3ac3e5bb>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00046] in <63e7c9910ab446ac9b78b1ac3ac3e5bb>:0 
  at xxx.Droid.MainActivity.OnStart () [0x00000] in <db697bb0cebf40899ddd1dbba31ef430>:0 
  at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <26ea6ddb724e4be2b66b6bde37c83c15>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.14(intptr,intptr)
       at crc6473e84085518c5ff7.MainActivity.n_onStart(MainActivity.java)
       at crc6473e84085518c5ff7.MainActivity.onStart(MainActivity.java:85)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
       at android.app.Activity.performStart(Activity.java:6032)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
       at android.app.ActivityThread.access$1200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

### Basic Information

```
Minimum Android version : Android 5.0 (API level 21)
Target Android version : Android 10.0 (API level 29)
=== Visual Studio Community 2019 for Mac ===

Version 8.6.2 (build 6)
Installation UUID: 69833a91-0eac-4ae5-b6a6-d5db1c20fbb4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Version: 3.1.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	2.1.18

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/todor/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.1
SDK Build Tools Version: 30.0.0 rc4

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/todor/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:22 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:42 UTC

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Build Information ===

Release ID: 806020006
Git revision: c742dc3fcbf76855738eef57ce41d65f91acbf27
Build date: 2020-05-28 15:22:51-04
Build branch: release-8.6
Xamarin extensions: c742dc3fcbf76855738eef57ce41d65f91acbf27

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

**Comment by grendello** [comment]
@todorspetkov is `libmono-native.so` found in in the APK?

**Comment by todorspetkov** [comment]
> @todorspetkov is `libmono-native.so` found in in the APK?

Yes libmono-native.so is present. The apk works on all Android platforms > SDK 21.

**Comment by grendello** [comment]
@todorspetkov I don't have enough information in the previous posts to be sure what's going on, but since it involves a native shared library, I guess that some of those devices lack some native symbols (for one reason or another) which prevents the native library from being loaded by the system. Note that the library is built by the Mono project with NDK against API 16 for 32-bit targets and against API 21 for 64-bit targets so it *should* work (and it does in a fair amount of tests both Mono and Xamarin.Android run). To further diagnose this, if you have access to a failing device, please follow [these steps](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#enable-logging-of-dlopen_dlsym-and-library-loading-errors-for-apps-available-in-android-o) and post a full logcat record (please issue `adb logcat -c` before dumping the logcat buffer, it will minimise noise) here.

**Comment by grendello** [comment]
Hm, actually, the steps I pointed out won't work... I've just noticed they're for Android O, Android 5.0 won't have the necessary support.

**Comment by grendello** [comment]
However, please enable all the possible logging in your application by issuing the following commands from command line before starting your application:

```shell
adb shell setprop debug.mono.env "MONO_LOG_LEVEL=debug|MONO_LOG_MASK=dll"
adb shell setprop debug.mono.log default,assembly
adb logcat -c
```
Then make sure to cold start the application and when it crashes, back on the command line, issue

```shell
adb logcat -d > log.txt
```

And attach the `log.txt` file here, hopefully it will tell us something more

**Comment by todorspetkov** [comment]
The error has been signaled by our users and I have seen it in firebase crashlytics. The stack traces I have included are from Firebase Robo device tests. I do not have a physical device with Android 5.0 where I can set adb shell properties... I will try to get one...

**Comment by grendello** [comment]
@todorspetkov I doubt it's just any 5.0 device. Some manufacturers were known to make changes to Android that broke compatibility, but never wholesale, it was always per-model (or sometimes even per Android build)

**Comment by todorspetkov** [comment]
Regarding this exception Firebase crashlytics says: 76% Huawei, 92% Android 5 devices... I was able to reproduce the crash in Firebase Test lab Robo on a Huawei P8 Lite API 21...

**Comment by grendello** [comment]
@todorspetkov So it looks like some Huawei-specific change that broke things. Were you able to enable the extra logging on that device (if it is even possible using the test lab)?

**Comment by todorspetkov** [comment]
I am not able to perform the adb shell operations you suggested in Test Lab. I will have to find a physical device thet crashes... It seems very hard these days to get your hands on a 2016 Huawei device running Android 5 :-).

**Comment by grendello** [comment]
It is quite ancient, indeed... :) I'm afraid there's no other way though :(

**Comment by brendanzagaeski** [comment]
By chance I was working today on a different issue that required additional logging, and for that issue I checked if it was possible to set the logging properties via an [environment file](https://docs.microsoft.com/xamarin/android/deploy-test/environment). That does seem to work, so if Firebase Test Lab Robo provides the `adb logcat` output from apps that run remotely, then adding an environment file to the APK might be a strategy for this issue too:

 1. Add a text file such as _environment.txt_ to the Xamarin.Android app project.

 2. Set the contents to:

    ```
    debug.mono.log=default,assembly
    MONO_LOG_LEVEL=debug
    MONO_LOG_MASK=dll
    ```

 3. Set the **Build Action** of the file to **AndroidEnvironment** in the **Properties** pane.

 4. Clean the solution and build the new APK. (Cleaning is

**Comment by todorspetkov** [comment]
> By chance I was working today on a different issue that required additional logging, and for that issue I checked if it was possible to set the logging properties via an [environment file](https://docs.microsoft.com/xamarin/android/deploy-test/environment). That does seem to work, so if Firebase Test Lab Robo provides the `adb logcat` output from apps that run remotely, then adding an environment file to the APK might be a strategy for this issue too:
> 
> 1. Add a text file such as _environment.txt_ to the Xamarin.Android app project.
> 2. Set the contents to:
>    ```
>    debug.mono.log=default,assembly
>    MONO_LOG_LEVEL=debug
>    MONO_LOG_MASK=dll
>    ```
> 3. Set the **Build Action** of the file to **AndroidEnvironment** in the **Properties** pane.
> 4. Clean the solution and build the new APK.

I performed these operations and am including the logcat output (quite long) in attachment.

[web-build_2020-06-10T08-20-36.809Z_iim9-hwALE-H-21-en_US-portrait-logcat.txt](https://github.com/xamarin/xamarin-android/files/4757159/web-build_2020-06-10T08-20-36.809Z_iim9-hwALE-H-21-en_US-portrait-logcat.txt)

**Comment by grendello** [comment]
So, the problem is shown here:

```
06-10 01:27:01.911: I/monodroid-assembly(21708): Trying to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'
06-10 01:27:01.921: I/monodroid-assembly(21708): Failed to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'. dlopen failed: could not load library "libmonosgen-2.0.so" needed by "/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so"; caused by library "libmonosgen-2.0.so" not found
06-10 01:27:01.921: I/monodroid-assembly(21708): Trying to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'
06-10 01:27:01.921: I/monodroid-assembly(21708): Failed to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'. dlopen failed: could not load library "libmonosgen-2.0.so" needed by "/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so"; caused by library "libmonosgen-2.0.so" not found
06-10 01:27:01.921: I/monodroid-assembly(21708): Trying to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'
06-10 01:27:01.921: I/monodroid-assembly(21708): Failed to load shared library '/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so'. dlopen failed: could not load library "libmonosgen-2.0.so" needed by "/data/app/it.giunko.junker-1/lib/arm64/./libmono-native.so"; caused by library "libmonosgen-2.0.so" not found
```                                                                                                                                                                                                         

Only this is not true... `libmonosgen-2.0.so` (the Mono runtime) is available and loaded, or otherwise the app wouldn't start at all (Xamarin.Android runtime depends on the same shared library) and also from the logs we see that the app is running its managed code, which means the Mono runtime was loaded, initialized and is
working properly.  My guess is that Huawei broke the bionic (Android libc) by (possibly?) reintroducing this [issue which was fixed in API level 18](https://issuetracker.google.com/issues/36950617) where Android wasn't able to follow shared library dependencies to load other required shared libraries (in this case `libmono-native.so` depends on `libmonosgen-2.0.so`). The dynamic linker should see that `libmonosgen-2.0.so` is already mapped into the process memory and resolve the dependency correctly, and that's how it works on other devices. At this point it's hard to say what the fix is because we still have only a vague idea on what's the underlying cause of the Huawei device behavior.

**Comment by todorspetkov** [comment]
Unfortunately I am still receiving this crash data for some Android SDK 21/22 devices...
Any idea what the cause/solution might be?

**Comment by grendello** [comment]
It's really hard to determine the cause without being able to access the device and the information we currently have appears to point to some problem with Huawei devices. However, I've just seen [this issue](https://github.com/xamarin/xamarin-android/issues/4852) which appears to be the same problem, but reproducible on an emulator. I'll try to reproduce it locally and will update the issues once I know anything more. In the meantime, @todorspetkov, could you check if you can reproduce the issue in an x86-64 Android 5.0/5.1 emulator?

**Comment by todorspetkov** [comment]
@grendello I setup two Virtual Devices using Android Studio, one using Android 5.0 (Google APIs) and one using Android 5.1 (Google APIs): on both I was able to reproduce the same crash.

**Comment by todorspetkov** [comment]
Update: I split our release build and produced an x86 only apk and a x86_64 only apk. On both virtual devices the x86 only apk runs fine. The x86_64 apk crashes.

**Comment by grendello** [comment]
@todorspetkov yes, x86 should run just fine on x86_64 and in real world the latter are few and far between, so you should be fine. Regarding the fix, please see the issue I linked to - I hope to have a PR up soon which will *probably* fix your problem as well.

**Comment by todorspetkov** [comment]
Ok, after going through the Google Play Console docs it seems that since Agust 1 2019, x86 cannot be included alone - one must also include x86_64 when publishing apps in the store ( 
https://developer.android.com/distribute/best-practices/develop/64-bit )...

So we will have to wait for the bug-fix...

**Comment by grendello** [comment]
@todorspetkov The above PR should fix your issue as well - on devices, in **Release** build.  The **Debug** build with shared runtime will **not** be fixed - please refer to [this comment](https://github.com/xamarin/xamarin-android/issues/4852#issuecomment-648395475) for explanation why :)

**Comment by todorspetkov** [comment]
Hi @grendello when do you expect this bugfix to make it into a xamarin-android official update? Really appreciate your help, thanks a lot.

**Comment by grendello** [comment]
@todorspetkov we first need to see the PR merged, I don't think we're going to see the fix in the upcoming 16.7 release, though. However, I can give you our Java startup code rebuilt with the fix so that you can replace it in your installation and rebuild your app with the fix. Please let me know if you'd like to do that, if only to test the fix.

**Comment by todorspetkov** [comment]
@grendello Yes I would like to try out the fix. I will probabely need instructions on what to do exactly :-).

**Comment by grendello** [comment]
[xa-java-runtime.zip](https://github.com/xamarin/xamarin-android/files/4824449/xa-java-runtime.zip)

@todorspetkov no worries, it's not that hard :). Download the attachment here, unpack it in some location. Then locate your Xamarin.Android installation tree, it should be in `C:\\Program Files (x86)\Microsoft Visual Studio\2019\[EDITION]\MSBuild\Xamarin\Android` - at this location you will find 4 files corresponding to the files in the above zip, make backup copies of the originals and replace them with those from the attached zip archive. Then rebuild your application from scratch (remove all `bin` and `obj`) and test.

**Comment by todorspetkov** [comment]
@grendello Ok I performed the steps you described and produced an apk that now runs on the Emulators without problems. Now I am running a battery of tests using Firebase Robo. Just a quick question: this fix is for Android 5.x devices based both on x86 and Arm platforms, right?

**Comment by grendello** [comment]
@todorspetkov great that it works for you! Yes, it's for all the supported architectures

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item (for apps built in the Release configuration).

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
