### ISSUE TITLE
XA5104: Could not locate the Android NDK. 

### ISSUE THREAD

**Issue by BananaSupreme** [xamarin/xamarin-android#6001]
I saw that people had this problem back in 2019 but it seems like most people agree it was just fixed which is why I opened a new issue...

### Steps to Reproduce

1. Fresh Installation of VS2019
2. Brand new project template
3. Enable AOT ![ArchiveTest](https://user-images.githubusercontent.com/75225915/120897514-43e86b80-c62f-11eb-8679-367c42ef186a.png)

4. Package

### Expected Behavior
create .apk

### Actual Behavior
XA5104: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path.
Done building project "ArchiveTest.Android.csproj" -- FAILED.

EDIT: if "Make bundle into native code" is enabled the error becomes: 
MSB4044: The "MakeBundleNativeCodeExternal" task was not given a value for the required parameter "AndroidNdkDirectory".

**Comment by jonathanpeppers** [comment]
Checking this box requires the Android NDK:

![image](https://user-images.githubusercontent.com/840039/121060110-d3a12d80-c787-11eb-8b7d-8de03542d2bf.png)

Do you have an Android NDK installed, such as:

![image](https://user-images.githubusercontent.com/840039/121060247-03503580-c788-11eb-82ff-a7bd6d07dda1.png)

**Comment by BananaSupreme** [comment]
Yes, i have the latest version installed.

**Comment by jonathanpeppers** [comment]
Can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?

Then try one of the 21.x versions to see if that solves the problem.

**Comment by BananaSupreme** [comment]
[2021-06-07_21-30-46.3248.sdkmanager.log](https://github.com/xamarin/xamarin-android/files/6618537/2021-06-07_21-30-46.3248.sdkmanager.log)

I couldn't run diagnostic logging due to some issue with hanging, some people reported it and I forwarded it to the visual studio team as well, 
I did find this in the logs with the line:
`[2021-06-07 21:30:47.4] DEBUG: [monodroid] Skipping NDK in 'C:\Program Files (x86)\Android\android-sdk\ndk\22.1.7171670': version 22.1.7171670 is out of the accepted range (major version must be between 16 and 21
[2021-06-07 21:30:47.4] DEBUG: [monodroid] Skipping NDK in 'C:\Program Files (x86)\Android\android-sdk\ndk-bundle': version 22.1.7171670 is out of the accepted range (major version must be between 16 and 21
[2021-06-07 21:30:47.4] DEBUG: [monodroid] ValidateAndroidNdkLocation: ``, result=False`


the 21 version works is found.
though im getting : XA3001: Could not AOT the assembly. to whatever the first assembly it tries to compile is, honestly all issues i could find blamed the linker so i just disabled it, should I open a new issue for this?

**Comment by jonathanpeppers** [comment]
All the issues above are AOT, not the linker.

Can you share more of the build log for the `Could not AOT the assembly` error?

**Comment by BananaSupreme** [comment]
[AOT log.txt](https://github.com/xamarin/xamarin-android/files/6618904/AOT.log.txt)

[AOT log 2.txt](https://github.com/xamarin/xamarin-android/files/6618903/AOT.log.2.txt)

I meant issues people reported...
Yes I uploaded 2 logs just to point that they crashed at different points.

Also I just want to say thank you for your help and quick replies, it is really greatly appreciated!

**Comment by jonathanpeppers** [comment]
What if you uncheck this box:

![image](https://user-images.githubusercontent.com/840039/121243769-b9d51880-c863-11eb-9334-eaee620eb7e5.png)

I think you're hitting the issue we fixed here: https://github.com/xamarin/xamarin-android/commit/6a5df165ed08103021d6ba79d8abd5dda671f825

```
[aot-compiler stdout] Executing opt: "D:\Software\Visual Studio\IDE\MSBuild\Xamarin\Android\opt" -f -O2 -disable-tail-calls -place-safepoints -spp-all-backedges -o "obj\Release\110\aot\armeabi-v7a\Xamarin.AndroidX.CardView.dll\temp.opt.bc" "obj\Release\110\aot\armeabi-v7a\Xamarin.AndroidX.CardView.dll\temp.bc"
XA3001: Could not AOT the assembly: Xamarin.Forms.Xaml.dll
```

It looks like the path has a space character in it, and we found an issue with that.

**Comment by BananaSupreme** [comment]
Success! I'll get around trying to install VS into a path without white space... 
Thanks again!

**Comment by pdsrebelo** [comment]
Hi @jonathanpeppers, I've been following the issue you just linked and I can see that the PR was merged into master a few days ago. Any idea of when that fix is available on the Microsoft agents that Azure DevOps uses?
I'm currently facing that issue on my Pipelines and can't think of a work-around to this issue, and unfortunately it's blocking my Xamarin builds at the moment.
Thanks in advance!

**Comment by jonathanpeppers** [comment]
@pdsrebelo a couple different issues are listed here, which one are you having exactly?

**Comment by pdsrebelo** [comment]
@jonathanpeppers, let me try to explain the issue I'm facing:

**Configuration:**
Both my local machine and the Microsoft Hosted Agent I'm using on Azure Devops are using the same Visual Studio version: 16.10.0.

The configuration I'm using has the following settings, regarding the AOT Compilation:
![image](https://user-images.githubusercontent.com/5577625/121374756-1275e580-c938-11eb-8944-ba97d29cb090.png)

**Azure DevOps:**
The issue started on Azure DevOps, as the build that I'm doing uses the task "Xamarin.Android" with the flag "Create app package" (which behind the scenes does a build with `/t:PackageForAndroid`). On that build, the error is the same as the one you've already fixed and merged into master (where the AOT compiler uses an incorrect path for the `C:\Program Files (x86)` folder).

I've also been using the flag `/p:AndroidNdkDirectory="path_to_ndk_folder"`, but for some reason, this flag doesn't seem to be used anymore? MSBuild completely ignores it, I think. Need clarification on this.

**Local machine:**
I was then able to reproduce the error locally, with a similar approach to what I'm doing on Azure DevOps, which is to use the Archive tool on Visual Studio. Whenever I do that, it indeed produces folder path error.

If I go into VS -> Tools -> Xamarin and change the Android SDK Location to something like "`C:\NDK`" everything works perfectly, as expected.

If I keep the default Android SDK Location (`C:\Program Files (x86)\Android\android-sdk`) and just disable the flag "Use LLVM Optimizing Compiler", it builds and generates the apk correctly as well.

So, my question is, how can I (without changing my configs to the AOT Compilation), build and generate an APK on Azure DevOps using this version of the Visual Studio?

(Hopefully I could explain my issue, but if you have any other questions, let me know!)

Thanks in advance!

**Comment by jonathanpeppers** [comment]
`/p:AndroidNdkDirectory="path_to_ndk_folder"` should work, do you have a build log showing that?

The options for workarounds for Azure DevOps would be:
* Turn off LLVM
* Use make a symbolic link (with [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)) to a working NDK that doesn't have spaces. Pass this to `/p:AndroidNdkDirectory`.
* Install a build of Xamarin.Android with the fix, you could try `boots --preview Xamarin.Android`: https://github.com/jonathanpeppers/boots

**Comment by charlesroddie** [comment]
> Both my local machine and the Microsoft Hosted Agent I'm using on Azure Devops are using the same Visual Studio version: 16.10.0.

Update: VS has been updated to 16.10.1 and this is in the 20210608.0 Azure Devops which has and this doesn't fix the issue since the fix hasn't gone into a Xamarin.Android release.

**Comment by jonathanpeppers** [comment]
To install a version with the fix:
```
# Windows
boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4829460/d16-10/ae14cafda4befc69867db19eee0728efec9cf71b/signed/Xamarin.Android.Sdk-11.3.0.4.vsix
# Mac
boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4829460/d16-10/ae14cafda4befc69867db19eee0728efec9cf71b/xamarin.android-11.3.0.4.pkg
```

**Comment by kevcrooks** [comment]
@jonathanpeppers thank you very much for this. We've just tried this with `boots` and this has fixed our DevOps pipeline now.

**Comment by kevcrooks** [comment]
If I'm reading the releases correctly, it looks like the latest Visual Studio 16.10.2 includes Xamarin.Android 11.3.0.4 released from this branch ([https://github.com/xamarin/xamarin-android/compare/d16-10](https://github.com/xamarin/xamarin-android/compare/d16-10))
which includes the fix for the issue (https://github.com/xamarin/xamarin-android/commit/89e702d4241a59b83edf0e3416327b06218b04c3)

So hopefully we can now wait for DevOps to update the Visual Studio versions to 16.10.2 on their build agents, and all should start working (I may have misread something though)?

**Comment by dellis1972** [comment]
We did cherry-pick the fix to 16.10 Service Release 2. So 🤞 devops will get it soon, I'm not sure how closely they track the releases.

**Comment by Happypig375** [comment]
VS17.0.4 somehow still has this issue.

**Comment by Happypig375** [comment]
```
Skipping NDK in 'C:\Program Files (x86)\Android\android-sdk
dk-bundle': version 22.1.7171670 is out of the accepted range (major version must be between 16 and 21
```

**Comment by Babai-42** [comment]
Hello. Ran into this problem today too: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path. The problem was solved by installing an older version of the NDK. I'm using the latest version of Visual Studio 2022, is this problem still not fixed? When can we expect a fix? What other options are there to solve this problem in my case? Will $(AndroidNdkDirectory) help? If yes, then you can write in more detail where to write this line with a forced path? What gives https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4829460/d16-10/ae14cafda4befc69867db19eee0728efec9cf71b/signed/Xamarin.Android.Sdk-11.3.0.4.vsix?

**Comment by jonathanpeppers** [comment]
This comment has an example of `/p:AndroidNdkDirectory`: https://github.com/xamarin/xamarin-android/issues/6001#issuecomment-857834407

If using an older NDK fixes your issue, then using the `AndroidNdkDirectory` property won't help either. Each version of Xamarin.Android has a maximum supported NDK version. Can you update Xamarin.Android instead?

**Comment by Babai-42** [comment]
I would love to update Xamarin.Android, but don't know how! Could you give me instructions. Visual Studio 2022 Windows 10 x64.

**Comment by Babai-42** [comment]
> This comment has an example of `/p:AndroidNdkDirectory`: [#6001 (comment)](https://github.com/xamarin/xamarin-android/issues/6001#issuecomment-857834407)
> 
> If using an older NDK fixes your issue, then using the `AndroidNdkDirectory` property won't help either. Each version of Xamarin.Android has a maximum supported NDK version. Can you update Xamarin.Android instead?

I would love to update Xamarin.Android, but don't know how! Could you give me instructions. Visual Studio 2022 Windows 10 x64.
