### ISSUE TITLE
Deploying app is unreliable for both Debug and Release builds

### ISSUE THREAD

**Issue by gmck** [xamarin/xamarin-android#6652]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.1.0 Prev 2.0

### Description

The last few weeks I’ve only been doing Debug builds and I’ve found that VS 2022 17.1.0 Prev 2 is not very reliable when it comes to deploying to the device. There doesn’t appear to be a pattern, just every now and then you get a message that the Deploy failed. Usually, it is because I tried a one stepper Build/Deploy. The build goes fine and at the end of the build, it starts to deploy and immediately fails. A normal clean/rebuild/deploy all separate steps then fails again on the deploy. The only way I’ve found to fix it is to close VS and start again and then it works fine until the next time it decides to fail which may be some hours later after plenty of good deploys in between.

Today I was ready for a Release build for Google Play. I swapped to Release, Clean, rebuild, deploy and it failed to deploy. Again, I exited VS and the next time it then created the aab and all was good with the upload to Google Play.
I’m attaching that particular build log as it demonstrates something that I thought was fixed sometime back last year. 

```
Task Parameter:ConsoleToMSBuild=True
Task Parameter:Command="C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s 0B251JEC218062 uninstall -k "com.glmsoftware.OBDNowPro"
"C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s 0B251JEC218062 uninstall -k "com.glmsoftware.OBDNowPro"
The -k option uninstalls the application while retaining the data/cache.
At the moment, there is no way to remove the remaining data.
You will have to reinstall the application with the same signature, and fully uninstall it.
If you truly wish to continue, execute 'adb shell cmd package uninstall -k'.
The command ""C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" -s 0B251JEC218062 uninstall -k "com.glmsoftware.OBDNowPro"" exited with code 1.
The previous error was converted to a warning because the task was called with ContinueOnError=true.
Build continuing because "ContinueOnError" on the task "Exec" is set to "True".
Done executing task "Exec" -- FAILED.

```
The warning still has no effect on the deployment, but it would be nice to get rid of it.

Later on, I realised that I’d forgotten to change a resource string in a dialog, so I made the change while it still was in Release. Built and deployed successfully and when I went to check the change, the string was as it was before I made the change. The same thing as before, exited VS and restarted and the next deploy contained the changed string. I don’t think I’ve ever seen that type of failure before when I’ve made a change in strings.xml

### Steps to Reproduce

AS above

### Did you find any workaround?

As above

### Relevant log output

```shell
Won't attach.
```

**Comment by gmck** [comment]
@dellis1972, @jonathanpeppers. I can't attach the file either way and it is way too big to paste. Will come up with a link later instead.

**Comment by gmck** [comment]
[ReleaseBuild1801202.zip](https://github.com/xamarin/xamarin-android/files/7894327/ReleaseBuild1801202.zip)

**Comment by dellis1972** [comment]
@gmck so is this log from the Release build which did not contain the changed file?

It would also be useful to see the deployment error your are getting when in Debug mode if you have that log too. 

Regarding the `The -k option uninstalls the application while retaining the data/cache.` warning. Unfortunately that is not something we can deal with. That warning is raised by adb itself. We can try to dig into the code to see what makes adb raise that warning, but its possible we might not be able to do anything about it. My experience is it happens when installing apk's which are signed with different keys, or have some resource changes which trigger this code path.

**Comment by dellis1972** [comment]
Looking at the log I'm seeing this
```
Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
```
Assuming this is a build when a resource file was changed that is a bit odd. It suggests that the file changed was not in the list of inputs for this target or the IDE hadn't saved it.

**Comment by gmck** [comment]
Re the release build. Well, I suppose if I'm installing a release build over a debug apk, then adb is correct because we are using different keys. Therefore I conclude that before deploying a release build as an aab, we should manually delete the previous debug apk from the device. I just thought that would have been automatic.

I thought I remembered you and @jonathanpeppers  discussing that on Discord some time ago and you said that check could probably be removed - actually, it might not have been you maybe someone else discussing with peppers.

**_Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files._**

Shouldn't the IDE save strings.xml if there has been a change as there was in this case? It certainly worked the next time I deployed - i.e. the altered string was then in the dialog.

Re the debug builds, I'll try and remember to save the logs the next time it happens.  I just get impatient at that point and restart the IDE and it is ok again the next time I deploy. That bug with the OK button took way too long to solve and the deploying problem wasn't helping with my patience. Will anyone check that example I uploaded to the forum or should I move it over to here?

The deployment error is just that - failed to deploy.

Why the problem with trying to attach logs? Can't remember that happening with the old issue templates.

**Comment by gmck** [comment]
@dellis1972 
I tried again with a Release build this morning. Prior to deploying I manually deleted the app from the device. Then I deployed and still got the same message re "The -k option uninstalls the application while retaining the data/cache etc.."  I tried finding that string on Discord - but no luck there. Maybe if you ask @jonathanpeppers, he may remember the conversation about it. As usual, no harm done, the app was deployed and ran normally with the latest change I had made.

I then swapped to a different device, deleted the app and tried to Deploy. I'm attaching the log of that one because that gave really weird stuff about - Missing APKs for [SCREEN_DENSITY] dimensions in the module 'base' for the provided device. Never seen that before.

Seems to me that the build doesn't recognise that the device has changed, even though VS indicates it has.

Cleaned rebuilt deployed and ran ok after that - also had the -k option message as above.

[ReleaseBuild20012022.txt](https://github.com/xamarin/xamarin-android/files/7900781/ReleaseBuild20012022.txt)

**Comment by gmck** [comment]
@dellis1972 
Just tried to deploy to another device. The app was not on the device, got the SCREEN_DENSITY stuff again. Shutdown and restarted VS and same thing again with the SCREEN_DENSITY warning.

Cleaned and rebuilt and deployed all ok, but still with the -k option warning. 

Anything else you want me to try?

**Comment by mreuterDyconTech** [comment]
@dellis1972 @jonathanpeppers Hi!
Since I updated VS to version 17.1 I'm facing the exact same problem as @gmck.

**Comment by uholeschak** [comment]
I have the same Problem with VS17.1.0.
Sometimes adb disconnect helps or switching for debug to release build or to another device temporarily.
Seems to be also a timing issue, sometimes it simply helps to retry deploying multiple times without any change and it suddenyl works again.
The android version of the device seems not to be the issue.

**Comment by dellis1972** [comment]
@mreuterDyconTech @uholeschak do you have diagnostic logs for the issues you are facing

see https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output 
and https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#device-deployment-logs

**Comment by dellis1972** [comment]
I've been doing some testing and I'm seeing this in the Xamarin logs (Help->Xamarin->Open Logs then open the latest ide log)

```
Xamarin.VisualStudio.Android.CommandHandlers.DeployCommandHandler Error: 0 : The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xamarin.VisualStudio.Build.BuildRunner.CreateRequestData(IProjectNode project, String target, IDictionary`2 properties) in D:\a\_work\1\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 209
   at Xamarin.VisualStudio.Build.BuildRunner.CreateSubmission(IProjectNode project, String target, IDictionary`2 globalProperties, ILogger defaultLogger) in D:\a\_work\1\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 252
   at Xamarin.VisualStudio.Build.BuildRunner.<RunAsync>d__9.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio\Build\BuildRunner.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Build.BuildCoordinator.<EnqueueAsync>d__12.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio\Build\BuildCoordinator.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.VisualStudio.Build.BuildCoordinator.<EnqueueAsync>d__12.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio\Build\BuildCoordinator.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.Services.AndroidToolsBuildService.<InstallPackageAsync>d__12.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.Android\Services\AndroidToolsBuildService.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.CommandHandlers.DeployCommandHandler.<DeployAsync>d__17.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.Android\CommandHandlers\DeployCommandHandler.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Android.CommandHandlers.DeployCommandHandler.<DeployAsync>d__16.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.Android\CommandHandlers\DeployCommandHandler.cs:line 291: 03/02/2022 11:25:43Z
    DateTime=2022-03-02T11:25:43.2346921Z: 03/02/2022 11:25:43Z
```

I'll ask the Visual Studio team (who maintain the extension) to take a look

**Comment by uholeschak** [comment]
After switching the Xamarin Diagnostics output to Detail it's not happening any more at the moment.
I expect this is a timing problem and the addition output delays operation.

**Comment by uholeschak** [comment]
Is this file helpful?
[2022-03-03_20-26-25.41364.Ide.log](https://github.com/xamarin/xamarin-android/files/8181367/2022-03-03_20-26-25.41364.Ide.log)

**Comment by uholeschak** [comment]
After updating to VS17.1.1 the problem still persist.
Closing the solution and reopening every time before deployment fixes the problem, but this is no solution ...

**Comment by AndreasSummer** [comment]
Have the same Problem with 17.1.2.

**Comment by uholeschak** [comment]
Yes the problem still persist in 17.1.2. Only closing and reopening the solution before every deployment helps.

**Comment by highwingers** [comment]
having same problem with VS 2022. I downloaded SyncFusion UI tools. and now i dont know how to deploy to my device. i cant open and close after every change.

**Comment by ledoods** [comment]
Chiming in to add that issue exists even in Version 17.2.0 Preview 2.1.

**Comment by highwingers** [comment]
any workaround for this? i even re-installed visual studio 2022 and then downloaded the latest version. same error about Deployment failure.

**Comment by uholeschak** [comment]
I only close the solution, but keep the VS open, and then reopen the last solution again. This is faster.

**Comment by dellis1972** [comment]
The internal Bug for VS has been marked as Resolved. Looking at the bug properties, they are planning to release this in 17.1 Preview 3.

**Comment by highwingers** [comment]
> I only close the solution, but keep the VS open, and then reopen the last solution again. This is faster.

how do you close solution?

**Comment by highwingers** [comment]
> The internal Bug for VS has been marked as Resolved. Looking at the bug properties, they are planning to release this in 17.1 Preview 3.
> 
> Related PR for VS extension https://github.com/xamarin/XamarinVS/pull/12880

404 page not found

**Comment by uholeschak** [comment]
> how do you close solution?
From the file menu.

**Comment by highwingers** [comment]
> Yes the problem still persist in 17.1.2. Only closing and reopening the solution before every deployment helps.

I restored my windows to last week..i am still on 17.1.2 and somehow no more errors.

**Comment by dellis1972** [comment]
> > The internal Bug for VS has been marked as Resolved. Looking at the bug properties, they are planning to release this in 17.1 Preview 3.
> > Related PR for VS extension [xamarin/XamarinVS#12880](https://github.com/xamarin/XamarinVS/pull/12880)
> 
> 404 page not found

Its a private repo. That link is there for reference so we can close this issue once the fix has been released.

**Comment by SpawnSP2** [comment]
VS updated today to 17.1.3, but the problem still persists.

**Comment by gmck** [comment]
@dellis1972 
The problem still persists in 17.2.0 Preview, so I wouldn't expect any earlier version to fix it. At least @uholeschak suggestion is much faster than closing VS and starting again. Are you sure that wasn't a typo re the internal bug etc...

**Comment by dellis1972** [comment]
It looks like the bug was label incorrectly :( I've asked the UI team for an update.

**Comment by symibsoft** [comment]
Same for me. VS updated today to 17.1.3, but the problem still persists.

**Comment by highwingers** [comment]
> > Yes the problem still persist in 17.1.2. Only closing and reopening the solution before every deployment helps.
> 
> I restored my windows to last week..i am still on 17.1.2 and somehow no more errors.

Never mind the windows restore trick. Problem came back.

**Comment by highwingers** [comment]
> It looks like the bug was label incorrectly :( I've asked the UI team for an update.

Please keep us posted.

**Comment by Manthazar** [comment]
I actually noticed that if you try often enough, at some time it starts to work again o.O.
Also, changing the Droid project causes this issue almost certainly while changing content in the xamarin project is not. 
Sometimes it seems to help to add a space somewhere in the droid project (even in c# parts) -maybe the rebuild and deploy is then having a different timing...

**Comment by SKeehnen** [comment]
I have the same issue. Not sure if it was only luck, but it looks like running VS in Admin mode makes it work.

**Comment by dellis1972** [comment]
I just had confirmation that the fix for this issue is shipping is 17.2 Preview 3.

**Comment by dellis1972** [comment]
The WorkItem can be found https://developercommunity.visualstudio.com/t/Deployment-error-on-debug-xamarin-androi/10006948

**Comment by mgierlasinski** [comment]
I can't believe such issues still happen and the only workoaround since 3 months is to reopen solution. For me every change to Android xml requires reopening solution. Hot reload can have many meanings...

**Comment by mfranke-moba** [comment]
Had the same problem. What helped me was switching to Visual Studio 2022 **LTSC**.

**Comment by uholeschak** [comment]
Using good old VS2019 is an option ...

**Comment by highwingers** [comment]
> Using good old VS2019 is an option ...

I am working on a .NET 6.0 project. its not an option for me. "Preview Release" did the trick for me.

**Comment by MagicAndre1981** [comment]
> I just had confirmation that the fix for this issue is shipping is 17.2 Preview 3.

17.2 P5 still has deployment issues.

**Comment by MagicAndre1981** [comment]
With 17.2 Preview 6 I now get errors about random files that are already in use and deploy is canceled...

**Comment by dellis1972** [comment]
@tondat are you able to shed any light on these issues? What data does the IDE team need to investigate?

**Comment by MagicAndre1981** [comment]
ok, the user @dsaf gave [me a hint that also works for me](https://github.com/xamarin/xamarin-android/issues/6975#issuecomment-1117125559). Running VS2022 **as admin** does the trick for me. Now my errors about files that are in use are gone and deploy also works fine 🤷‍♂️

**Comment by dellis1972** [comment]
Anyone with an issue can you do the following please

Please run `devenv /log` to open the IDE. Repo the issue then get the ide logs from `%localappdata%\Xamarin\Logs\17.0` and post them here.

**Comment by dsaf** [comment]
> Anyone with an issue can you do the following please
> 
> Please run `devenv /log` to open the IDE. Repo the issue then get the ide logs from `%localappdata%\Xamarin\Logs\17.0` and post them here.

Annoyingly enough, I cannot reproduce it straight away anymore. Perhaps, running VS as admin released or cleared something. I will keep running VS in a non-admin mode and keep an eye. I also tend to use Hibernate option in Windows, which not many people do, instead of leaving the machine on or shutting it down. Not sure if related or not.

**Comment by MagicAndre1981** [comment]
for me the issue still happens in 17.3 P1.1 and this time running VS as admin doesn't fix it
