### ISSUE TITLE
VS doesn't show physical device - getting AdbException on "getprop" step

### ISSUE THREAD

**Issue by FoggyFinder** [xamarin/xamarin-android#8329]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022 - 17.7.3; Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)

### Description

Not sure it's the right place to open issue but can't think of anything better. 

adb correctly detects physical device while VS doesn't add it to the list. There're plenty of similar Qs on SO:

https://stackoverflow.com/questions/70224238/visual-studio-2022-android-device-not-found
https://stackoverflow.com/questions/25888188/visual-studio-doesnt-let-me-debug-on-android-physical-device

Tried to install different drivers, turn on/off debug allowance, change connection options,... And nothing.

Logs from Xamarin.Diagnostics:

```
[I:]:                     Got new device list from adb with 1 devices
[D:RunShellCommand]:      IREQJ7DU85YPAQEI getprop
-- Start GetProperties - 09/12/2023 17:00:39 (43.4969ms) --
[INPUT] getprop
[OUTPUT]
[Build.BRAND]: [MTK]
// ... other properties are omitted
[vold.storage.prepared]: [1]
-- End GetProperties --
[E:]:                     Error getting properties from device 'IREQJ7DU85YPAQEI'
Mono.AndroidTools.AdbException: Unknown property format: ']'
   at Mono.AndroidTools.Internal.AdbOutputParsing.ParseGetprop(String properties) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 104
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.AndroidDevice.<RefreshProperties>d__52.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.DevicePropertiesTracker.<GetAndAnnotatePropertiesAsync>d__9.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDeviceManager.cs:line 532
```

### Steps to Reproduce

no repro, didn't see this issue on other systems

### Did you find any workaround?

nope

**Comment by jonpryor** [comment]
This is a duplicate of: https://developercommunity.visualstudio.com/t/Connecting-to-Android-device-Newland-f/10424915

This was fixed on 2023-Aug-12 in: https://github.com/xamarin/androidtools/commit/09dce7939bc4fcba2c970103c3ff4eb3c065804b

Unfortunately, the fix has not yet been released.  Commit 29c7de2a85e6b12b5233ed79067e23b8667a0c63 contains the fix, which in turn is included in our (forthcoming) .NET 8 RC1 release, *and* we'll also need the IDEs to pick up this fix as well.  (Hopefully Visual Studio (Windows) 17.8 Preview 3 will contain this fix.)

In the meantime/as a workaround, find the "offending" system property and remove it, if possible.

Which property is the "offending" system property?  The one that has `]` without a preceding `[` on the same line when reading `adb shell getprop`.

For example, the following `adb shell setprop` command creates a `debug.multiline.example` system property which will cause the `Unknown property format` error:

```sh
% adb shell setprop debug.multiline.example '"GT1158[0x19]
"'
```

When reading `adb shell getprop`, you'll see:

```sh
% adb shell getprop
…
[debug.multiline.example]: [GT1158[0x19]
]
…
```

To "fix" the error, remove the offending system property:

```sh
% adb shell setprop debug.multiline.example '""'
```

Note: this only works if you *can* modify the offending system property…

**Comment by FoggyFinder** [comment]
sadly, wasn't able to edit the property

**Comment by FoggyFinder** [comment]
thank you, fixed in VS2022 preview indeed!

**Comment by hansmbakker** [comment]
@jonpryor @jonathanpeppers @dellis1972 is this fixed, meaning that https://developercommunity.visualstudio.com/t/ADB-GetProps-Parsing-Regression-in-VS-20/10490234 is a different issue in the same place?

Visual Studio 17.8 preview 6 did not fix that issue for me unfortunately.

**Comment by dellis1972** [comment]
@hansmbakker that issue is caused by the following
`[persist.vendor.radio.ut.xui.info_2]: [kah2#,1)-))±11/18aek&l]d]cge&]]`

Notice the miss matching `]` characters. This threw off the fix that we put in place for this issue. 
We have engineered a newer solution which I think will be out in dotnet rc2.1 that should fix this newer issue.

**Comment by hansmbakker** [comment]
@dellis1972 according to https://github.com/xamarin/xamarin-android/releases/tag/34.0.0-rc.2.479, Visual Studio 17.8 preview 6 should contain that rc2.1, but it did not fix that issue for me

**Comment by dellis1972** [comment]
@hansmbakker do you still get the same ""Multi-line processing failed for getprops" error? if so the new "fix" probably didn't make it in, since we remove that error completely.

**Comment by dellis1972** [comment]
@hansmbakker 
 I'll put this here too, this line

```
[ro.boot.ddrsize.range]: [[1024,2048)]
```

Is probably what is throwing off the old parser. note the number of [ and ] do not match up. There is a [ and a ) instead. 
Not sure if that is something you can change. 

That said the new fix we put in place does not rely on matching up brackets, so it can handle this kind of data.

**Comment by hansmbakker** [comment]
> do you still get the same ""Multi-line processing failed for getprops" error?

@dellis1972 Yes I do:
```
Mono.AndroidTools.AdbException: Multi-line processing failed for getprops: ''
```

**Comment by paulocarinhena** [comment]
It's a problem that happens to me.
Version 17.7.x did not have this problem. 
Affects  > 18.0.x

**Comment by Shannon-roos** [comment]
This is still an issue with 2022 Preview 2.0 released today... 

Is there any other workaround that can be done without rooting the device?

**Comment by dellis1972** [comment]
You need 17.8.3 to get the fix.

**Comment by Shannon-roos** [comment]
Based on the community post about it [here ](https://developercommunity.visualstudio.com/t/Android-local-devices-stops-appearing-af/10515028) I thought so too but I get the same behaviour on 17.8.3.

I have tried with multiple Android devices and multiple development machines. Some updated, others new installs...

For completeness, this is Xamarin Diagnostics stack trace. This gets thrown whenever I plug in a device.

`System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Mono.AndroidTools.AndroidLogger.LogWarning(String task, String format, Object[] args) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidLogger.cs:line 42
   at Mono.AndroidTools.Internal.AdbOutputParsing. <ParseGetprop>g__AddProperty|3_0(<>c__DisplayClass3_0& ) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 112
   at Mono.AndroidTools.Internal.AdbOutputParsing.ParseGetprop(String properties) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 97
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.AndroidDevice. <RefreshProperties>d__52.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.DevicePropertiesTracker. <GetAndAnnotatePropertiesAsync>d__9.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDeviceManager.cs:line 532`

**Comment by dellis1972** [comment]
@Shannon-roos 

ok that is a different issue than the one reported. Can you open a new issue and attach the exception as the results of the following call from an "Adb Command Prompt" when you have this particular device plugged in.

```
adb shell getprop
```

**Comment by Shannon-roos** [comment]
> @Shannon-roos
> 
> ok that is a different issue than the one reported. Can you open a new issue and attach the exception as the results of the following call from an "Adb Command Prompt" when you have this particular device plugged in.
> 
> ```
> adb shell getprop
> ```

Ah Apologies. Will open a new one then.
