### ISSUE TITLE
Unable to connect Android device to Visual Studio 2022 17.8

### ISSUE THREAD

**Issue by t4e-dev** [xamarin/xamarin-android#8514]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS2022 17.8

### Description

After updating to Visual Studio 2022 17.8 we are unable to connect to a Nokia T20 device

Xamarin Diagnostic outputs:

`
[E:]:                     Error getting properties from device '4000TA13921B2401654'
Mono.AndroidTools.AdbException: Multi-line processing failed for getprops: ''
   at Mono.AndroidTools.Internal.AdbOutputParsing.ParseGetprop(String properties) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 120
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.AndroidDevice.<RefreshProperties>d__52.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.AndroidTools.DevicePropertiesTracker.<GetAndAnnotatePropertiesAsync>d__9.MoveNext() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDeviceManager.cs:line 532
`

adb shell getprops

`
[build.version.extensions.r]: [4]
[build.version.extensions.s]: [4]
[cache_key.bluetooth.get_adapter_connection_state]: [8282041925313328269]
[cache_key.bluetooth.get_bond_state]: [8282041925313328265]
[cache_key.bluetooth.get_profile_connection_state]: [8282041925313328270]
[cache_key.bluetooth.get_state]: [8282041925313328271]
[cache_key.bluetooth.is_offloaded_filtering_supported]: [8282041925313328266]
[cache_key.display_info]: [-6495984980114073376]
[cache_key.get_packages_for_uid]: [-6495984980114073375]
[cache_key.has_system_feature]: [-6495984980114073859]
[cache_key.is_compat_change_enabled]: [-6495984980114073402]
[cache_key.is_interactive]: [-6495984980114073382]
[cache_key.is_power_save_mode]: [-6495984980114073563]
[cache_key.is_user_unlocked]: [-6495984980114073761]
[cache_key.location_enabled]: [-6495984980114073845]
[cache_key.package_info]: [-6495984980114073401]
[cache_key.system_server.account_user_data]: [-6495984980114073395]
[cache_key.system_server.accounts_data]: [-6495984980114073760]
[cache_key.telephony.get_active_data_sub_id]: [3387632888780523311]
[cache_key.telephony.get_default_data_sub_id]: [3387632888780523307]
[cache_key.telephony.get_default_sms_sub_id]: [3387632888780523308]
[cache_key.telephony.get_default_sub_id]: [3387632888780523306]
[cache_key.telephony.get_slot_index]: [3387632888780523310]
[camera.disable_zsl_mode]: [1]
[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.dex2oat-max-image-block-size]: [524288]
[dalvik.vm.dex2oat-minidebuginfo]: [true]
[dalvik.vm.dex2oat-resolve-startup-strings]: [true]
[dalvik.vm.dex2oat-updatable-bcp-packages-file]: [/system/etc/updatable-bcp-packages.txt]
[dalvik.vm.dexopt.secondary]: [true]
[dalvik.vm.dexopt.thermal-cutoff]: [2]
[dalvik.vm.heapgrowthlimit]: [256m]
[dalvik.vm.heapmaxfree]: [16m]
[dalvik.vm.heapminfree]: [4m]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [16m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [generic]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.isa.arm64.variant]: [generic]
[dalvik.vm.madvise.artfile.size]: [4294967295]
[dalvik.vm.madvise.odexfile.size]: [104857600]
[dalvik.vm.madvise.vdexfile.size]: [104857600]
[dalvik.vm.minidebuginfo]: [true]
[dalvik.vm.usejit]: [true]
[dalvik.vm.usejitprofiles]: [true]
[debug.atrace.tags.enableflags]: [0]
[debug.force_rtl]: [false]
[debug.tracing.screen_brightness]: [0.0]
[debug.tracing.screen_state]: [1]
[debug.vendor.nhmonitor.delay30dump]: [false]
[debug.vendor.nhmonitor.status]: [true]
[dev.bootcomplete]: [1]
[dev.mnt.blk.data]: [dm-37]
[dev.mnt.blk.data.user.0]: [dm-37]
[dev.mnt.blk.data_mirror.cur_profiles]: [dm-37]
[dev.mnt.blk.data_mirror.data_ce.null]: [dm-37]
[dev.mnt.blk.data_mirror.data_ce.null.0]: [dm-37]
[dev.mnt.blk.data_mirror.data_de.null]: [dm-37]
[dev.mnt.blk.data_mirror.ref_profiles]: [dm-37]
[dev.mnt.blk.odm]: [dm-36]
[dev.mnt.blk.odm.6000F]: [dm-36]
[dev.mnt.blk.odm.600CLA]: [dm-36]
[dev.mnt.blk.odm.600EEA]: [dm-36]
[dev.mnt.blk.odm.600EEA_WIFI]: []
[dev.mnt.blk.odm.600RU]: [dm-36]
[dev.mnt.blk.odm.600RU_WIFI]: [dm-36]
[dev.mnt.blk.odm.600WW]: [dm-36]
[dev.mnt.blk.odm.600WW_WIFI]: [dm-36]
[dev.mnt.blk.odm.app]: [dm-36]
[dev.mnt.blk.odm.etc.permissions]: [dm-36]
[dev.mnt.blk.product]: [dm-34]
[dev.mnt.blk.root]: [dm-31]
[dev.mnt.blk.system_ext]: [dm-32]
[dev.mnt.blk.vendor]: [dm-33]
[dev.mnt.blk.vendor_dlkm]: [dm-35]
[graphics.gpu.profiler.support]: [true]
[gsm.current.phone-type]: [1]
[gsm.network.type]: [Unknown]
[gsm.operator.alpha]: []
[hwservicemanager.ready]: [true]
[init.svc.adbd]: [running]
[init.svc.apexd]: [stopped]
[init.svc.apexd-bootstrap]: [stopped]
[init.svc.apexd-snapshotde]: [stopped]
[init.svc.app_hibernation]: [stopped]
[init.svc.aprd]: [stopped]
[init.svc.audioserver]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.boringssl_self_test32]: [stopped]
[init.svc.boringssl_self_test32_vendor]: [stopped]
[init.svc.boringssl_self_test64]: [stopped]
[init.svc.boringssl_self_test64_vendor]: [stopped]
[init.svc.boringssl_self_test_apex32]: [stopped]
[init.svc.boringssl_self_test_apex64]: [stopped]
[init.svc.bpfloader]: [stopped]
[init.svc.cameraserver]: [running]
[init.svc.check_keymaster]: [stopped]
[init.svc.cmd_services]: [stopped]
[init.svc.credstore]: [running]
[init.svc.derive_classpath]: [stopped]
[init.svc.derive_sdk]: [stopped]
[init.svc.drm]: [running]
[init.svc.ext_data]: [running]
[init.svc.gatekeeperd]: [running]
[init.svc.gpu]: [running]
[init.svc.gsid]: [running]
[init.svc.health-hal-2-1]: [running]
[init.svc.heapprofd]: [stopped]
[init.svc.hidl_memory]: [running]
[init.svc.hwservicemanager]: [running]
[init.svc.idmap2d]: [stopped]
[init.svc.incidentd]: [running]
[init.svc.insmod-sh]: [stopped]
[init.svc.installd]: [running]
[init.svc.ip_monitor]: [running]
[init.svc.keystore2]: [running]
[init.svc.linkturbonative]: [running]
[init.svc.lmkd]: [running]
[init.svc.log_service]: [running]
[init.svc.logd]: [running]
[init.svc.logd-auditctl]: [stopped]
[init.svc.logd-reinit]: [stopped]
[init.svc.media]: [running]
[init.svc.media.swcodec]: [running]
[init.svc.media.unisoc.codec2]: [running]
[init.svc.mediadrm]: [running]
[init.svc.mediaextractor]: [running]
[init.svc.mediametrics]: [running]
[init.svc.minidumpd]: [stopped]
[init.svc.netd]: [running]
[init.svc.neuralnetworks_hal_service_xtensa]: [running]
[init.svc.nhmonitor]: [stopped]
[init.svc.odsign]: [stopped]
[init.svc.oemlock-hal-1-0]: [running]
[init.svc.performancemanager]: [running]
[init.svc.phasecheckserver]: [running]
[init.svc.sar_wifi_off]: [stopped]
[init.svc.sar_wifi_on]: [stopped]
[init.svc.servicemanager]: [running]
[init.svc.slogmodem]: [running]
[init.svc.snapuserd]: [running]
[init.svc.sprd_networkcontrol]: [running]
[init.svc.statsd]: [running]
[init.svc.storaged]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.systemDebuggerd]: [stopped]
[init.svc.system_suspend]: [running]
[init.svc.tombstoned]: [running]
[init.svc.traced]: [running]
[init.svc.traced_perf]: [stopped]
[init.svc.traced_probes]: [running]
[init.svc.ueventd]: [running]
[init.svc.uniber]: [running]
[init.svc.update_engine]: [running]
[init.svc.update_verifier_nonencrypted]: [stopped]
[init.svc.usb-hal-1-1]: [running]
[init.svc.usbd]: [stopped]
[init.svc.vold]: [running]
[init.svc.wait_for_keymaster]: [stopped]
[init.svc.watchdogd]: [stopped]
[init.svc.wificond]: [running]
[init.svc.wpa_supplicant]: [running]
[init.svc.ylog]: [running]
[init.svc.yloglite]: [stopped]
[init.svc.zygote]: [running]
[init.svc.zygote_secondary]: [running]
[log.tag.APM_AudioPolicyManager]: [D]
[log.tag.stats_log]: [I]
[media.stagefright.thumbnail.prefer_hw_codecs]: [true]
[net.bt.name]: [Android]
[net.qtaguid_enabled]: [1]
[ota.warm_reset]: [0]
[partition.odm.verified]: [2]
[partition.odm.verified.hash_alg]: [sha256]
[partition.product.verified]: [2]
[partition.product.verified.hash_alg]: [sha256]
[partition.system.verified]: [2]
[partition.system.verified.hash_alg]: [sha256]
[partition.system_ext.verified]: [2]
[partition.system_ext.verified.hash_alg]: [sha256]
[partition.vendor.verified]: [2]
[partition.vendor.verified.hash_alg]: [sha256]
[partition.vendor_dlkm.verified]: [2]
[partition.vendor_dlkm.verified.hash_alg]: [sha256]
[persist.default.rotation]: [1]
[persist.device_config.runtime_native.metrics.reporting-mods]: [0]
[persist.device_config.runtime_native.metrics.reporting-mods-server]: [0]
[persist.device_config.runtime_native.metrics.reporting-num-mods]: [100]
[persist.device_config.runtime_native.metrics.reporting-num-mods-server]: [100]
[persist.device_config.runtime_native.metrics.write-to-statsd]: [false]
[persist.device_config.runtime_native.usap_pool_enabled]: [true]
[persist.device_config.runtime_native.use_app_image_startup_cache]: [true]
[persist.device_config.runtime_native_boot.disable_lock_profiling]: [false]
[persist.device_config.runtime_native_boot.enable_uffd_gc_2]: [false]
[persist.device_config.runtime_native_boot.force_disable_uffd_gc]: [false]
[persist.device_config.runtime_native_boot.iorap_blacklisted_packages]: []
[persist.device_config.runtime_native_boot.iorap_perfetto_enable]: [false]
[persist.device_config.runtime_native_boot.iorap_readahead_enable]: [false]
[persist.device_config.runtime_native_boot.iorapd_options]: []
[persist.emdoor.ambient.Notifications]: [0]
[persist.memorypolicy.cleanup.enabled]: [true]
[persist.memorypolicy.fastkill.enabled]: [true]
[persist.netmon.linger]: [10000]
[persist.radio.multisim.config]: [ssss]
[persist.storage.type]: [2]
[persist.sys.3d.calibraion]: [1]
[persist.sys.apr.autoupload]: [1]
[persist.sys.apr.enabled]: [0]
[persist.sys.apr.exceptionnode]: [0]
[persist.sys.apr.intervaltime]: [1]
[persist.sys.apr.lifetime]: [0]
[persist.sys.apr.reload]: [0]
[persist.sys.apr.reportlevel]: [2]
[persist.sys.apr.rlchanged]: [800]
[persist.sys.apr.testgroup]: [CSSLAB]
[persist.sys.apr.timechanged]: [180]
[persist.sys.audio.source]: [true]
[persist.sys.boot.reason]: []
[persist.sys.boot.reason.history]: [reboot,ota,1700203991
reboot,userrequested,ota_updbug,1700203921
reboot,ota,1700126776]
[persist.sys.cam.3dnr]: [true]
[persist.sys.cam.beauty.filter.enable]: [true]
[persist.sys.cam.beauty.fullfuc]: [true]
[persist.sys.cam.eois.dc.back]: [false]
[persist.sys.cam.eois.dc.front]: [false]
[persist.sys.cam.eois.dv.back]: [true]
[persist.sys.cam.eois.dv.front]: [false]
[persist.sys.cam.fast.blur]: [false]
[persist.sys.cam.manual.focus]: [true]
[persist.sys.cam.manual.shutter]: [true]
[persist.sys.cam.wide.8M]: [true]
[persist.sys.cam.wide.power]: [true]
[persist.sys.cam3.multi.cam.id]: [2]
[persist.sys.cam3.type]: [back_blur]
[persist.sys.cmdservice.enable]: [disable]
[persist.sys.csvt]: [false]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.displayinset.top]: [0]
[persist.sys.fflag.override.settings_fuse]: [true]
[persist.sys.fuse]: [true]
[persist.sys.fuse.passthrough.enable]: [true]
[persist.sys.gms]: [1]
[persist.sys.heartbeat.enable]: [1]
[persist.sys.isolated_storage]: [true]
[persist.sys.lmk.reportkills]: [true]
[persist.sys.locale]: [de-DE]
[persist.sys.navbar.overlay]: [false]
[persist.sys.power.touch]: [0]
[persist.sys.pq.cabc.enabled]: [1]
[persist.sys.pq.enabled]: [1]
[persist.sys.pwctl.appidle]: [1]
[persist.sys.pwctl.appidle.force]: [1]
[persist.sys.pwctl.appstats]: [0]
[persist.sys.pwctl.bgclean]: [1]
[persist.sys.pwctl.enable]: [1]
[persist.sys.pwctl.gps]: [1]
[persist.sys.pwctl.gps.onlysave]: [0]
[persist.sys.pwctl.guru]: [1]
[persist.sys.pwctl.onlysave]: [0]
[persist.sys.pwctl.wl]: [1]
[persist.sys.sdcardfs]: [force_on]
[persist.sys.setupwizard.join_user_experience_program]: [false]
[persist.sys.ss.enable]: [true]
[persist.sys.ss.habit]: [true]
[persist.sys.ss.hmm]: [true]
[persist.sys.ss.predict]: [false]
[persist.sys.ss.scene]: [true]
[persist.sys.ss.scroll]: [false]
[persist.sys.ss.sr.enable]: [true]
[persist.sys.ss.track]: [true]
[persist.sys.ss.uhc.enable]: [true]
[persist.sys.support.vt]: [true]
[persist.sys.timezone]: [Europe/Berlin]
[persist.sys.usb.config]: [adb]
[persist.system.sar_wifi]: [1]
[persist.traced.enable]: [1]
[persist.vendor.bsservice.enable]: [1]
[persist.vendor.faceid.livenessgrade]: [2]
[persist.vendor.faceid.livenessmode0]: [0]
[persist.vendor.keybox.ready]: [FALSE]
[persist.vendor.keymaster.ready]: [TRUE]
[persist.vendor.nhmonitor]: [on]
[pm.dexopt.ab-ota]: [speed-profile]
[pm.dexopt.bg-dexopt]: [speed-profile]
[pm.dexopt.boot-after-ota]: [verify]
[pm.dexopt.cmdline]: [verify]
[pm.dexopt.first-boot]: [verify]
[pm.dexopt.inactive]: [verify]
[pm.dexopt.install]: [speed-profile]
[pm.dexopt.install-bulk]: [speed-profile]
[pm.dexopt.install-bulk-downgraded]: [verify]
[pm.dexopt.install-bulk-secondary]: [verify]
[pm.dexopt.install-bulk-secondary-downgraded]: [extract]
[pm.dexopt.install-fast]: [skip]
[pm.dexopt.post-boot]: [extract]
[pm.dexopt.shared]: [speed]
[ro.actionable_compatible_property.enabled]: [true]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [0]
[ro.apex.updatable]: [true]
[ro.audio.whale_hal]: [true]
[ro.baseband]: [unknown]
[ro.board.platform]: [ums512]
[ro.boot.auto.chipid]: [UMS512-AC]
[ro.boot.auto.efuse]: [T610]
[ro.boot.avb_version]: [1.2]
[ro.boot.board_type]: [wifi_only]
[ro.boot.boot_devices]: [soc/soc:ap-apb/71400000.sdio]
[ro.boot.bootreason]: [reboot,ota]
[ro.boot.ddrsize]: [4096M]
[ro.boot.ddrsize.range]: [[4096,5120)]
[ro.boot.dswdten]: [disable]
[ro.boot.dtbo_idx]: [1]
[ro.boot.dynamic_partitions]: [true]
[ro.boot.efused]: [1]
[ro.boot.factoryresettime]: [1659629984967]
[ro.boot.flash.locked]: [1]
[ro.boot.force_normal_boot]: [1]
[ro.boot.hardware]: [ums512_1h10]
[ro.boot.hardware.revision]: [V1.0]
[ro.boot.hef]: [0]
[ro.boot.lwfq.type]: [1]
[ro.boot.product.hardware.sku]: [wifionly]
[ro.boot.product.vendor.sku]: [sprd]
[ro.boot.serialno]: [4000TA13921B2401654]
[ro.boot.skuid]: [600EEA]
[ro.boot.slot_suffix]: [_b]
[ro.boot.vbmeta.avb_version]: [1.1]
[ro.boot.vbmeta.device_state]: [locked]
[ro.boot.vbmeta.digest]: [b07f16e70cc98862e318acd5292d80cdeb386986f5c9bb31b34d5a725a0852c9]
[ro.boot.vbmeta.hash_alg]: [sha256]
[ro.boot.vbmeta.invalidate_on_error]: [yes]
[ro.boot.vbmeta.size]: [49856]
[ro.boot.vendor.skip.init]: [0]
[ro.boot.verifiedbootstate]: [green]
[ro.boot.veritymode]: [enforcing]
[ro.boot.versiontype]: [600EEA_WIFI]
[ro.boot.wallpapered]: [0]
[ro.boot.wdten]: [e551]
[ro.bootanimation.orientation]: [90]
[ro.bootimage.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.bootimage.build.date.utc]: [1695204784]
[ro.bootimage.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.bootimage.build.id]: [SP1A.210812.016]
[ro.bootimage.build.tags]: [release-keys]
[ro.bootimage.build.type]: [user]
[ro.bootimage.build.version.incremental]: [00WW_2_38E]
[ro.bootimage.build.version.release]: [12]
[ro.bootimage.build.version.release_or_codename]: [12]
[ro.bootimage.build.version.sdk]: [31]
[ro.bootloader]: [unknown]
[ro.bootmode]: [unknown]
[ro.build.ab_update]: [true]
[ro.build.characteristics]: [tablet]
[ro.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.build.date.utc]: [1695204784]
[ro.build.description]: [Riddler_user_12_SP1A.210812.016_00WW_2_38E_release-keys]
[ro.build.display.id]: [00WW_2_380_SP04]
[ro.build.fingerprint]: [Nokia/RiddlerWifi_00EEA/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.build.flavor]: [Riddler-user]
[ro.build.host]: [build45]
[ro.build.id]: [SP1A.210812.016]
[ro.build.product]: [RDD]
[ro.build.product.name]: [RiddlerWifi_00EEA]
[ro.build.software.subversion]: [B01]
[ro.build.software.version]: [V2.38E]
[ro.build.system_root_image]: [false]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [longru]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_380:user/release-keys]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [00WW_2_38E]
[ro.build.version.min_supported_target_sdk]: [23]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.preview_sdk_fingerprint]: [REL]
[ro.build.version.release]: [12]
[ro.build.version.release_or_codename]: [12]
[ro.build.version.sdk]: [31]
[ro.build.version.security_patch]: [2023-09-05]
[ro.camerax.extensions.enabled]: [true]
[ro.carrier]: [oversea]
[ro.com.android.dataroaming]: [false]
[ro.com.android.prov_mobiledata]: [false]
[ro.com.google.clientidbase]: [android-hmd]
[ro.com.google.clientidbase.ms]: [android-hmd-rvo3]
[ro.com.google.clientidbase.tx]: [android-hmd-rvo3]
[ro.com.google.clientidbase.vs]: [android-hmd-rvo3]
[ro.com.google.gmsversion]: [12_202210]
[ro.config.alarm_alert]: [Nk_Alarm_Clock.ogg]
[ro.config.notification_sound]: [Nk_Message_1.ogg]
[ro.config.ringtone]: [Nk_Tune.ogg]
[ro.control_privapp_permissions]: [enforce]
[ro.crypto.dm_default_key.options_format.version]: [2]
[ro.crypto.metadata.enabled]: [true]
[ro.crypto.state]: [encrypted]
[ro.crypto.type]: [file]
[ro.crypto.uses_fs_ioc_add_encryption_key]: [true]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [0]
[ro.frp.pst]: [/dev/block/by-name/persist]
[ro.hardware]: [ums512_1h10]
[ro.hardware.egl]: [mali]
[ro.hwui.use_vulkan]: []
[ro.iorapd.enable]: [true]
[ro.launcher.desktopgrid]: [true]
[ro.launcher.dynamic]: [false]
[ro.launcher.multimode]: [true]
[ro.launcher.notifbadge.count]: [false]
[ro.lmk.critical]: [100]
[ro.lmk.kill_heaviest_task]: [true]
[ro.lmk.kill_timeout_ms]: [200]
[ro.lmk.low]: [950]
[ro.lmk.medium]: [800]
[ro.lmk.use_minfree_levels]: [true]
[ro.logd.size.stats]: [64K]
[ro.media.recoderEIS.enabled]: [true]
[ro.media.wfd.resolution]: [2]
[ro.media.wfd.rgb.enabled]: [true]
[ro.minui.hwrotation]: [90]
[ro.netflix.channel]: [a0936ad0a17611eab9d55b5e87136a35]
[ro.netflix.signup]: [1]
[ro.odm.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.odm.build.date.utc]: [1695204784]
[ro.odm.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.odm.build.version.incremental]: [00WW_2_38E]
[ro.opa.eligible_device]: [true]
[ro.opengles.version]: [196610]
[ro.organization_owned]: [true]
[ro.postinstall.fstab.prefix]: [/product]
[ro.product.ab_ota_partitions]: [boot,mmcblk0boot1,trustos,sml,teecfg,vbmeta,vbmeta_system,vbmeta_system_ext,vbmeta_vendor,vbmeta_product,vbmeta_odm,dtbo,uboot,vendor_boot,l_modem,l_agdsp,l_cdsp,l_gdsp,l_ldsp,pm_sys,l_fixnv1,l_fixnv2,l_deltanv,system,system_ext,vendor,product,odm,vendor_dlkm,boot]
[ro.product.assistanttouch]: [false]
[ro.product.board]: [Riddler]
[ro.product.bootimage.brand]: [Nokia]
[ro.product.bootimage.device]: [RDD]
[ro.product.bootimage.manufacturer]: [HMD Global]
[ro.product.bootimage.model]: [Nokia T20]
[ro.product.bootimage.name]: [RiddlerWifi_00EEA]
[ro.product.brand]: [Nokia]
[ro.product.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.product.build.date.utc]: [1695204784]
[ro.product.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.product.build.id]: [SP1A.210812.016]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [00WW_2_38E]
[ro.product.build.version.release]: [12]
[ro.product.build.version.release_or_codename]: [12]
[ro.product.build.version.sdk]: [31]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [RDD]
[ro.product.first_api_level]: [30]
[ro.product.hardware]: [ums512_1h10]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [HMD Global]
[ro.product.model]: [Nokia T20]
[ro.product.model.display]: [TA-1392]
[ro.product.model.num]: [00EEA]
[ro.product.model.ready]: [true]
[ro.product.name]: [RiddlerWifi_00EEA]
[ro.product.nickname]: [Nokia T20]
[ro.product.odm.brand]: [Nokia]
[ro.product.odm.device]: [RDD]
[ro.product.odm.manufacturer]: [HMD Global]
[ro.product.odm.model]: [Nokia T20]
[ro.product.odm.name]: [RiddlerWifi_00EEA]
[ro.product.product.brand]: [Nokia]
[ro.product.product.device]: [RDD]
[ro.product.product.manufacturer]: [HMD Global]
[ro.product.product.model]: [Nokia T20]
[ro.product.product.name]: [RiddlerWifi_00EEA]
[ro.product.system.brand]: [Nokia]
[ro.product.system.device]: [Riddler_00WW]
[ro.product.system.manufacturer]: [HMD Global]
[ro.product.system.model]: [Nokia T20]
[ro.product.system.name]: [RiddlerWifi_00EEA]
[ro.product.system_ext.brand]: [Nokia]
[ro.product.system_ext.device]: [RDD]
[ro.product.system_ext.manufacturer]: [HMD Global]
[ro.product.system_ext.model]: [Nokia T20]
[ro.product.system_ext.name]: [RiddlerWifi_00EEA]
[ro.product.vendor.brand]: [Nokia]
[ro.product.vendor.device]: [RDD]
[ro.product.vendor.manufacturer]: [HMD Global]
[ro.product.vendor.model]: [Nokia T20]
[ro.product.vendor.name]: [RiddlerWifi_00EEA]
[ro.product.vendor_dlkm.brand]: [Nokia]
[ro.product.vendor_dlkm.device]: [RDD]
[ro.product.vendor_dlkm.manufacturer]: [HMD Global]
[ro.product.vendor_dlkm.model]: [Nokia T20]
[ro.product.vendor_dlkm.name]: [RiddlerWifi_00EEA]
[ro.product.vndk.version]: [31]
[ro.property_service.version]: [2]
[ro.radio.dataonly]: [0]
[ro.radio.noril]: [1]
[ro.revision]: [0]
[ro.revoke.frequency.millis]: [864000000]
[ro.revoke.threshold.millis]: [4320000000]
[ro.secure]: [1]
[ro.serialno]: [4000TA13921B2401654]
[ro.setupwizard.rotation_locked]: [true]
[ro.sf.lcd_density]: [280]
[ro.sf.lcd_height]: [96]
[ro.sf.lcd_width]: [54]
[ro.simlock.onekey.lock]: [0]
[ro.simlock.unlock.autoshow]: [1]
[ro.simlock.unlock.bynv]: [0]
[ro.soc.manufacturer]: [Spreadtrum]
[ro.soc.model]: [T618]
[ro.sprd.displayenhance]: [true]
[ro.sprd.nightdisplay.enhance]: [true]
[ro.sprd.pwctl.ultra.message]: [1]
[ro.sprd.superresolution]: [1]
[ro.sr.displaysize.defaultresolution]: [0]
[ro.sr.displaysize.lowresolution]: [1]
[ro.storage.flash_type]: [2]
[ro.support_one_handed_mode]: [true]
[ro.surface_flinger.force_hwc_copy_for_virtual_displays]: [false]
[ro.surface_flinger.has_HDR_display]: [false]
[ro.surface_flinger.has_wide_color_display]: [false]
[ro.surface_flinger.max_frame_buffer_acquired_buffers]: [3]
[ro.surface_flinger.max_virtual_display_dimension]: [0]
[ro.surface_flinger.present_time_offset_from_vsync_ns]: [0]
[ro.surface_flinger.primary_display_orientation]: [ORIENTATION_0]
[ro.surface_flinger.running_without_sync_framework]: [false]
[ro.surface_flinger.set_display_power_timer_ms]: [1000]
[ro.surface_flinger.set_idle_timer_ms]: [80]
[ro.surface_flinger.set_touch_timer_ms]: [200]
[ro.surface_flinger.start_graphics_allocator_service]: [false]
[ro.surface_flinger.support_kernel_idle_timer]: [true]
[ro.surface_flinger.use_content_detection_for_refresh_rate]: [true]
[ro.surface_flinger.use_context_priority]: [true]
[ro.surface_flinger.use_vr_flinger]: [false]
[ro.surface_flinger.vsync_event_phase_offset_ns]: [1000000]
[ro.surface_flinger.vsync_sf_event_phase_offset_ns]: [1000000]
[ro.sys.pwctl.ultrasaving]: [1]
[ro.sys.sdcardfs]: [true]
[ro.system.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.system.build.date.utc]: [1695204784]
[ro.system.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.system.build.id]: [SP1A.210812.016]
[ro.system.build.tags]: [release-keys]
[ro.system.build.type]: [user]
[ro.system.build.version.incremental]: [00WW_2_38E]
[ro.system.build.version.release]: [12]
[ro.system.build.version.release_or_codename]: [12]
[ro.system.build.version.sdk]: [31]
[ro.system.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.system.product.cpu.abilist64]: [arm64-v8a]
[ro.system_ext.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.system_ext.build.date.utc]: [1695204784]
[ro.system_ext.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.system_ext.build.id]: [SP1A.210812.016]
[ro.system_ext.build.tags]: [release-keys]
[ro.system_ext.build.type]: [user]
[ro.system_ext.build.version.incremental]: [00WW_2_38E]
[ro.system_ext.build.version.release]: [12]
[ro.system_ext.build.version.release_or_codename]: [12]
[ro.system_ext.build.version.sdk]: [31]
[ro.telephony.default_network]: [9]
[ro.treble.enabled]: [true]
[ro.unisoc.lmkd.fix]: [20221201]
[ro.vendor.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.vendor.build.date.utc]: [1695204784]
[ro.vendor.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.vendor.build.id]: [SP1A.210812.016]
[ro.vendor.build.security_patch]: [2023-09-05]
[ro.vendor.build.tags]: [release-keys]
[ro.vendor.build.type]: [user]
[ro.vendor.build.version.incremental]: [00WW_2_38E]
[ro.vendor.build.version.release]: [12]
[ro.vendor.build.version.release_or_codename]: [12]
[ro.vendor.build.version.sdk]: [31]
[ro.vendor.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.vendor.product.cpu.abilist64]: [arm64-v8a]
[ro.vendor_dlkm.build.date]: [Wed Sep 20 10:13:04 UTC 2023]
[ro.vendor_dlkm.build.date.utc]: [1695204784]
[ro.vendor_dlkm.build.fingerprint]: [Nokia/Riddler_00WW/RDD:12/SP1A.210812.016/00WW_2_38E:user/release-keys]
[ro.vendor_dlkm.build.id]: [SP1A.210812.016]
[ro.vendor_dlkm.build.tags]: [release-keys]
[ro.vendor_dlkm.build.type]: [user]
[ro.vendor_dlkm.build.version.incremental]: [00WW_2_38E]
[ro.vendor_dlkm.build.version.release]: [12]
[ro.vendor_dlkm.build.version.release_or_codename]: [12]
[ro.vendor_dlkm.build.version.sdk]: [31]
[ro.virtual_ab.compression.enabled]: [true]
[ro.virtual_ab.enabled]: [true]
[ro.vm.socket.disable]: [true]
[ro.vndk.version]: [31]
[ro.wifi.channels]: []
[ro.zygote]: [zygote64_32]
[security.perf_harden]: [1]
[selinux.restorecon_recursive]: [/data/misc_ce/10]
[service.sf.present_timestamp]: [1]
[service.wait_for_bootanim]: [1]
[setupwizard.feature.baseline_setupwizard_enabled]: [true]
[setupwizard.theme]: [glif_v3_light]
[sys.boot.reason]: [reboot,ota]
[sys.boot.reason.last]: [reboot,userrequested,ota_update]
[sys.boot_completed]: [1]
[sys.bootstat.first_boot_completed]: [1]
[sys.debug.fwc]: [0]
[sys.fuse.transcode_enabled]: [true]
[sys.hmd.frameworks_version]: [0.12.27]
[sys.init.perf_lsm_hooks]: [1]
[sys.internal.emulated]: [1]
[sys.oem_unlock_allowed]: [0]
[sys.rescue_boot_count]: [1]
[sys.sysctl.extra_free_kbytes]: [28125]
[sys.system_server.start_count]: [1]
[sys.system_server.start_elapsed]: [152158]
[sys.system_server.start_uptime]: [152158]
[sys.usb.config]: [adb]
[sys.usb.configfs]: [1]
[sys.usb.controller]: [musb-hdrc.1.auto]
[sys.usb.mode]: [normal]
[sys.usb.state]: [adb]
[sys.use_memfd]: [false]
[sys.user.0.ce_available]: [true]
[sys.wifitracing.started]: [1]
[sys.ylog.bootimes]: [1]
[sys.ylog.version]: [4.1.03]
[sys.ylog.wbootimes]: [1]
[sys.zramwb_flag]: [1001]
[vendor.thermal.maxbrightness]: [255]
[vold.checkpoint_committed]: [1]
[vold.emulated.volume.ready]: [1]
[vold.has_adoptable]: [1]
[vold.has_compress]: [0]
[vold.has_quota]: [0]
[vold.has_reserved]: [1]

`

### Steps to Reproduce

Connect Nokia T20 ( Android 12 ) and enable debug settings

### Did you find any workaround?

No

**Comment by dellis1972** [comment]
This is a duplicate of [#8329](https://github.com/xamarin/xamarin-android/issues/8329)  which is fixed in .net 8. You should try to upgrade to the latest.
Unfortunately there is no workaround unless we can find the offending property and remove or alter it. That can usually only be done on a device which has been rooted. 

If this is still an issue after upgrading place reopen this issue.

**Comment by t4e-dev** [comment]
Hi. @dellis1972 
Thanks for your quick support. 
As mentioned above: I am on the latest VS2022 Version 17.8 ( including .NET8 )
So this seems to be definitely not fixed...

**Comment by dellis1972** [comment]
Your bug report states `.NET Android (net7.0-android, etc.)`. If you are still targeting .net 7 (even if you have .net 8 installed) you won't get the fix. I tested your  `adb getprops` output against our old version and it failed in the manner you reported. I also tested it aginst the fixed assembly and it worked. 

Can you check your app is targeting .net8.0-android?

**Comment by t4e-dev** [comment]
.net7 comes from the dropbox here in GitHub :)
Yeah we are targetting net8.

**Comment by dellis1972** [comment]
@jonathanpeppers can you remmber if we bumped androidtools to include this commit for .net 8 https://github.com/xamarin/androidtools/pull/399.

**Comment by dellis1972** [comment]
Doh, looks like this one missed the .net 8 release , it was only commited to the 17-8 branch 16 hours ago :( https://github.com/xamarin/androidtools/commits/d17-8

**Comment by dellis1972** [comment]
@t4e-dev 

If it helps this is the line causing the problem

`[ro.boot.ddrsize.range]: [[4096,5120)]`

Note the unballanced `[` `]` in there. Its throwing off our parser.

**Comment by t4e-dev** [comment]
Yes. Thanks. 
I noticed that and tried to use adb shell setprop.... But you mentioned it above... We would need root for that...
Is there another option for me to get around the issue by setting something on the device ?

**Comment by dellis1972** [comment]
Not that I'm aware of. @jonpryor any ideas on how we could work around this one?

**Comment by t4e-dev** [comment]
Is there an expected release date for the next VS2022 17.8 version ?

**Comment by jonathanpeppers** [comment]
> @jonathanpeppers can you remmber if we bumped androidtools to include this commit for .net 8 [xamarin/androidtools#399](https://github.com/xamarin/androidtools/pull/399).

I think I see this change in here: https://github.com/xamarin/xamarin-android/compare/34.0.0-rc.2.479...34.0.43

* https://github.com/xamarin/monodroid/commits/47bdaaa9b8ac16d6197a8982c8cc810d177c5cff
* https://github.com/xamarin/androidtools/commits/a91687438076fbb9bc5a34201bbc15503eb913e2

@t4e-dev are you seeing the message *inside* Visual Studio? Perhaps the change is missing in the Xamarin/MAUI extension for Visual Studio.

This looks like the log window in VS:
```
 [E:]:                     Error getting properties from device '4000TA13921B2401654' Mono.AndroidTools.AdbException: Multi-line processing failed for getprops: '' at Mono.AndroidTools.Internal.AdbOutputParsing.ParseGetprop(String properties) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 120 at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke()
```

**Comment by dellis1972** [comment]
@jonathanpeppers it looks like its the IDE extensions then I guess. That exception has been completely removed in the new code. The VS IDE Extension needs a bump I think.

**Comment by t4e-dev** [comment]
I See the Message inside Visual Studio in the Xamarin Diagnostic tab in the output ..

**Comment by Zou-Jia** [comment]
Hi, I am facing the same issue. Since this has been fixed, is there anything i can do on my side like manually patch the IDE extension? Or I have to wait for the next VS release?

**Comment by dellis1972** [comment]
I'm afraid you will have to wait for the next release. The IDE extension which needs the fix ships with Visual Studio itself. 
That said the assembly in question is `Xamarin.AndroidTools.dll` . If you can find that in the .net Android SDK Pack, you might be able to copy that assembly over to where the IDE extension has its copy. 

The only problem there is we use strong naming for all assemblies, so the IDE extension might not like the new version as it will be looking for the old reference.

**Comment by t4e-dev** [comment]
Hi. Are we speaking of days, weeks or  months for the next release ? :-)
Thanks for your support!

**Comment by t4e-dev** [comment]
@dellis1972  : Today there was an update to 17.8.1 but the issue is still not fixed...

**Comment by Zou-Jia** [comment]
![image](https://github.com/xamarin/xamarin-android/assets/14681050/ec341e05-d7c5-49f0-95ec-b55b05fb74f2)
Not sure if I am looking at the right place, according to @dellis1972 , the issue is fix at d17-8. Hoping next release will have the fix included

**Comment by dellis1972** [comment]
@tondat do we have an ETA on when this might be released?

**Comment by paulocarinhena** [comment]
This error happens to me too. It's a complicated error because it prevents you from doing something important: debugging.

I hope they can resolve it soon, please.

**Comment by kunzflorian** [comment]
Update 18.2 has neither fixed the problem.

```
adb devices
adb -s "<deviceIDfromlist>" install "<path-to-apk>"
```
... are working as expected. I'm questioning myself, whether there may be a workaround.

Is manually editing the launchsettings.json maybe an option?

```
{
  "profiles": {
    "Windows Machine": {
      "commandName": "MsixPackage",
      "nativeDebugging": false
    }
  }
}
```
I reckon the xamarinsdk, is extending it automatically for the users....
But googling about lead me nowhere...
Can anyone give me a hint whether this could be possible and where to read more about it ? :/

Regards,
Florian

P.S.: Murphies law had hit the VS maui survey  :) I just cant answere it, before this has been fixed.. i <3 maui/xamarin/mono

**Comment by Rotundjeree** [comment]
Hi guys! Have same issue with Nokia G22. I described problem on Microsoft Q&A and Developer Community, here links:
1. https://learn.microsoft.com/en-us/answers/questions/1443617/visual-studio-2022-doesn-t-see-android-device-at-a
2. https://developercommunity.visualstudio.com/t/Unable-to-deploy-a-MAUI-application-to-a/10530613

**Comment by dellis1972** [comment]
I believe the fix for the IDE extension has been merged and should ship in 17.8.2 (I beleive) @tondat can you confirm that?

**Comment by kunzflorian** [comment]
Hm. I don't think 17.8.2 has fixed automatically.... Are there any others steps to do after the update?

![image](https://github.com/xamarin/xamarin-android/assets/82371295/4e6f2056-28ed-4fd9-b47f-5eb4f363f0b9)

![image](https://github.com/xamarin/xamarin-android/assets/82371295/69070700-2677-4e27-bc8d-b701538e86af)

![image](https://github.com/xamarin/xamarin-android/assets/82371295/51983e69-537d-4d20-8af0-5b24c9dd52f4)

**Comment by dellis1972** [comment]
Ok, I'm probably mixed up on the VS version numbers. What ever the next release is going to be.

**Comment by Rotundjeree** [comment]
They promise to fix this in pending release according to this discussion: https://developercommunity.visualstudio.com/t/Android-local-devices-stops-appearing-af/10515028
A work around for now is: 
![изображение_2023-12-01_125157822](https://github.com/xamarin/xamarin-android/assets/105885733/d6d21aba-78c2-48e8-bfb3-2c42786e8f67)

**Comment by alejandro7x** [comment]
I confirm it also happens to me after upgrading to version **17.8.2**, installing **17.9.0 Preview 1.1** (and restarting the computer) the device is again recognized for debugging, in this case we are working with Xamarin Forms projects.

**Comment by kunzflorian** [comment]
Hey @t4e-dev ,

I have updated to version 17.8.3

![image](https://github.com/xamarin/xamarin-android/assets/82371295/f9dbb71f-230f-4df4-8a12-37eb5a948096)

and my devices working as expected. I just had to accept a preview-license...

To me the bug is solved, can u confirm?

Regards,
Florian

**Comment by t4e-dev** [comment]
Hi. Yes I can confirm this too. My devices are also available again.
